Dockerfile
README.md
docs/CONTRIBUTING.md

Once a container using this image is run, it will serve a `hello world` message.
In order to locally build Athenian web app image, and run it, run:
```bash
$ docker build --tag=athenian-app .
$ docker run --rm --publish=8080:80 --name=athenian-app athenian-app
```
Then you can open http://localhost:8080 in your browser, and see the Athenian web app.

Add Dockerfile creating nginx image

---

.dockerignore
.travis.yml
Dockerfile

fix [[ENG-4]]
relates to [[ENG-6]]
Once this is merged, we will have the webapp dockerized, and running tests and builds from Travis as in this example in mi personal Travis account:
:point_right:  https://travis-ci.org/dpordomingo/athenian-webapp/builds/621079586
**TODO:**
- `docker push` is not yet ready, because I don't know where are we pushing.
[ENG-4]: https://athenianco.atlassian.net/browse/ENG-4
[ENG-6]: https://athenianco.atlassian.net/browse/ENG-6

Dockerize the webapp

---

src/sass/main.scss
src/sass/overrides.scss

blocked by #19
_Changes to be reviewed only by 1127c522bf056a2798c4398c1ee1a4550370855b_
Override bootstrap grid sizes to fit athenian layout:
Main new values:
- grid-gutter-width: 20px instead of 30px
- grid-breakpoints: xl -> 1300px instead of 1200px
- container-max-widths: xl -> 1270px instead of 1140px
see original values at https://getbootstrap.com/docs/4.3/layout/grid/#variables

Override bootstrap grid sizes to fit athenian layout

---

src/App.js
src/services/api.js

fix [[ENG-83]] Call the API to fill the cards with the data returned
This PR calls the API to get thumbnails metrics. It's still a _poc_ to be evolved as we start adding use cases and have real data and stop mocking.
The following improvements in the API side would be very welcome in the frontend:
- [[ENG-122]] Only zero-values in `lead-time`, `wait-first-review-time`, `merging-time` and `release-time`
Some thumbnails lack chart because per [[ENG-122]] its metrics returns only `zero-values`.
[ENG-83]: https://athenianco.atlassian.net/browse/ENG-83
[ENG-125]: https://athenianco.atlassian.net/browse/ENG-125
[ENG-122]: https://athenianco.atlassian.net/browse/ENG-122

ENG-83 Use API metrics from thumbnails

---

src/components/charts/CleanAreaChart.js
src/components/pipeline/PipelineCard.js

Pipeline thumbnails should be smaller.
Its charts were not properly rendered because of a lack of config.
Before:
After:
Design:

Fix pipeline thumb chart sizing

---

Dockerfile
Makefile

There was a problem rebuilding node-gyp which also seems to need python2 and is not available. It's fixed in the latest release of `node-alpine`.
I guess the error appeared when trying to build any new dependency added (or updated) by https://github.com/athenianco/athenian-webapp/pull/25
Also it was needed the  inside the image in order run 'make' commands to install and build the app

[Hotfix] Update node-alpine base image

---

src/js/App.jsx
src/js/components/development/index.jsx
src/js/components/development/index.scss

used by #43 and #44
When running the project development (`make serve`), it will appear in the right-bottom corner a small container revealing the current breakpoint based in current bootstrap config.
The compiled version (`make build`) does not add this helper.

Add Development.Breakpoints tool to reveal breakpoints

---

src/js/pages/Home.jsx
src/js/pages/templates/Page.jsx
src/js/services/api/index.js
src/js/services/api/openapi-client/ApiClient.js
src/js/services/api/openapi-client/api/DefaultApi.js

This adds the authentication header with the bearer token required by the api.
For now, it has been added only to `getUser` and `getPipelineDataAPI`. I'd suggest refactoring better the code once we have more calls to the apis. So far I just copy-pasted the same snippet of code for the two above mentioned api calls.
The first commit simply updates the client code according to the updated spec that includes security schema.

Add Bearer auth header for api calls

---

src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/Stage.jsx
src/js/pages/templates/Page.jsx

caused by https://github.com/athenianco/athenian-webapp/pull/46#discussion_r373456996
This hotfix will:
- let the visitor see data as guest (using guest user, as automatically set by the API)
- if after logging the API can not process the token from Auth0, it will be shown an empty user but keeping the 'isAuthenticated' state, so the user will still be able to logout.

Fix guest feature, and workaround for API fails

---

src/js/App.jsx
src/js/Routes.jsx
src/js/pages/auth/Callback.jsx
src/js/pages/auth/Login.jsx

this will update #50
- Let the user know that is going to accept an invitation,
- Show errors that can happen when accepting an invitation:
- when trying to accept an invitation being already logged in,
- when the API is not responding,
- when the invitation is not valid,
- when the acceptance process crashed.
- Logout the user if the handshake could not be performed
(so they can retry)
Other minors:
- Homogenize the new routes with the current ones
- Clean leftover
When trying to accept an invitation being logged:
When accepting an invitation, and login is requested:
When the invitation is no valid

Improve UX when accepting invitations

---

src/js/App.jsx
src/js/Routes.jsx
src/js/pages/auth/Callback.jsx
src/js/pages/auth/Login.jsx
src/js/services/api/index.js

This PR implements the followings:
- add a redirect from url matching the format of the admin invitation link to the login page,
- add the invitation link to the `appState` of Auth0 to make it available in the callback,
- change the Auth0 callback handler to always redirect to `/callback`,
- call `/v1/accept` endpoint of api if the invitation link correspond to an admin link,
- redirect to waiting page on succes.

Auth handshake webapp <> api

---

src/js/components/pipeline/PullRequests.jsx
src/js/res/palette.js
src/js/services/format.js
src/sass/_typography.scss
src/sass/_variables.scss
src/sass/main.scss

depends on https://github.com/athenianco/athenian-webapp/pull/60
depends on https://github.com/athenianco/athenian-webapp/pull/65
depends on https://github.com/athenianco/athenian-webapp/pull/66
This PR integrates the PRs from the context into the PRs table in the overview section.
The PR table lets the user to paginate, sort columns and filter by participants, stage, PR status...
It is only needed to review 467941d (the rest of the commits, are in the PRs listed above)

Integrate PRs into overview

---

.gitignore
Makefile
src/js/services/api/openapi.v0.0.39.yaml

caused by https://github.com/athenianco/athenian-webapp/pull/75/files#r383942255
Once a new API schema is successfully used to autogenerate the API client, its sources will be stored into as 'src/js/services/api/openapi.v*.yaml' and the old ones will be removed.

Persist the current API schema

---

src/js/components/layout/Breadcrumbs.jsx
src/js/components/layout/Navbar.jsx
src/sass/_overrides.scss
src/sass/base/_typography.scss
src/sass/components/_badges.scss
src/sass/components/_dropdowns.scss
src/sass/components/_tables.scss
src/sass/layout/_header.scss

This PR is related to the task [#ENG-276](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-276). I refactored the sizing of all spacer elements and typography sizes to make it more intuitive to work according to the pixel sizes on the prototypes and the rem units, refactoring everything to make `1rem = 10px`.
I added new custom spacer sizes and fixed some minor issues after the refactor to keep it looking as it was previously.

Refactoring sizes for spacers and type sizes to make it more intuitive

---

Makefile

Make is automatically checking built-in rules for every target it runs wich may cause uncontrolled issues if that Make feature is now known and used on purpose.
This feature can be disabled if running it with `-r` or adding it to the `MAKEFLAGS`.
Disabling this feature also helps when debugging a Makefile because there will be output way fewer rules (only the explicit ones, and no tons of the Make built-in ones)
read more at https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html

Enhance debug experience on Makefiles

---

src/sass/components/_tables.scss

This is the first task on the issue [#ENG-281](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-281). It fixes the sorting icons on the PR tables:

Fixing table sort icons

---

src/sass/components/_pipeline.scss

This is a task from the issue [#ENG-281](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-281)
I fixes a minor bug on the pipeline so now all elements will be aligned even when they don't have content.

Adding fixed height to pipeline tabs

---

src/sass/components/_tooltips.scss
src/sass/main.scss

This task is related to the issue [#ENG-281](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-281).
It fixes the tooltips styles to make them match the prototypes

Adding style to the tooltips

---

src/js/components/pipeline/PullRequests.jsx
src/sass/_overrides.scss

This task is related to the issue [#ENG-281](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-281)
I fixed the alignment of the PR tabs and also changed the highlight color to the proper light orange:

Centered alignment of the PR tabs

---

src/js/components/pipeline/StageMetrics.jsx
src/js/pages/prototypes/Prototypes.jsx
src/sass/base/_typography.scss

This is related to the issue [#ENG-281](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-281).
It improves the Insights adding proper padding and sizes to the elements.

Improving the Insights styles

---

src/js/components/layout/Navbar.jsx
src/js/components/ui/CopyButton.jsx
src/js/smart-components/InvitationCreator.jsx
src/sass/base/_typography.scss
src/sass/components/_dropdowns.scss

This task is based on the issue [#ENG-281](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-281)
I fixed the styles on the User Dropdown to make it match the prototypes:

Fixing User Dropdown Styles

---

src/js/components/layout/Navbar.jsx
src/js/components/pipeline/PullRequests.jsx
src/js/components/ui/CopyButton.jsx
src/js/res/palette.js
src/js/smart-components/InvitationCreator.jsx
src/sass/_overrides.scss
src/sass/_variables.scss
src/sass/base/_typography.scss
src/sass/components/_badges.scss
src/sass/components/_dropdowns.scss
src/sass/components/_tables.scss

This task is based on the issue [#ENG-286](https://athenianco.atlassian.net/browse/ENG-286?atlOrigin=eyJpIjoiOGVkZTk3OTVjZmVhNGNiMzhkMzUyZDJkMmM1MTMzODEiLCJwIjoiaiJ9) and related to the PR #97.
I reorganized and refactored the color variables to have only variables on `_overrides.scss` and all the color definitions on `_variables.scss`.

Reorganizing color variables

---

package.json
src/js/Routes.jsx
src/js/pages/datefilter/DateFilter.jsx
src/sass/components/_datepicker.scss
src/sass/main.scss
yarn.lock

This is related to the issue [#ENG-292](https://athenianco.atlassian.net/browse/ENG-292?atlOrigin=eyJpIjoiMGFlNDJjOTFjOTkwNDU1MWEzZjFlZTNiMTgxN2RhZmIiLCJwIjoiaiJ9) and it adds the library [rb-datepicker](https://atkawa7.github.io/rb-datepicker) to add a new date picker dropdown. It can be checked on http://localhost:3000/datefilter
It is stilly missing a proper behavior on the real dropdown once it is reviewed and approved.

Adding a new calendar library and template for the date dropdown

---

.travis.yml
src/js/components/pipeline/StageMetrics.jsx

It is needed to deploy the `/prototypes/datefilter` into staging to be reviewed by Product even with breaking tests.
This will be reverted once Staging is deployed.

Force deploy staging

---

package.json
src/sass/components/_datepicker.scss
src/sass/main.scss
yarn.lock

caused by https://github.com/athenianco/athenian-webapp/pull/104#discussion_r390524614
This addresses the suggestion made by https://github.com/athenianco/athenian-webapp/pull/104#discussion_r390524614, importing the styles from [`daterangepicker/blob/master/daterangepicker.css`](https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.css) and overriding only what was different between that one and the older [`src/sass/components/_datepicker.scss`](https://github.com/athenianco/athenian-webapp/blob/a053537b744ebc578440c664f452d1404835256a/src/sass/components/_datepicker.scss)

Use imported bootstrap-daterangepicker styles

---

docs/SummaryMetrics.md
src/js/components/charts/FilledAreaChart.jsx
src/js/components/pipeline/StageMetrics.jsx
src/js/components/pipeline/Thumbnails.jsx
src/js/context/Pipeline.jsx
src/js/pages/Pipeline.jsx
src/js/pages/pipeline/Body.jsx
src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/Pipeline.jsx
src/js/pages/pipeline/Stage.jsx
src/js/services/api/index.js
src/js/services/format.js
src/sass/components/_pipeline.scss

This PR adds the Summary Charts into Overview and to all the pipeline stages.
- fef6c1a It is added a new chart: `FilledAreaChart`
- d8d6436 Add SummaryMetric component into Overview and each Stage; It's using already retrieved `prs`, `leadtime` and `stages` which are stored in `PRsContext` and `PipelineContext`. There is no data calculation in this commit, so it's used mocked data instead.
- ed5c3e5 Calculates the aggregations needed for the Summary Metrics following ￼[DesignDoc](https://docs.google.com/document/d/1DXLVz4L1Ag9sOUMAKdRRgVh1fk6peUrvVIp2xzeCRzQ)

Add Summary Metrics chart into Overview & Stages

---

src/js/components/pipeline/StageMetrics.jsx
src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/Stage.jsx

The purpose of this PR is to reduce future conflicts. Since @dpordomingo you're going to add the `Insights` tab and I'm going to implement the charts inside that tab, I'd rather better split the summary block from the insights one.
So that I'll work on the Insights component and on the other hand you're free to move it when you'll implement the tab mechanism.

Better separation between the summary and the insights section

---

public/config.js

This removes the need to use personal accounts for both GH and Auth0.

Fix config.js in order to use athenian development tenant

---

src/js/pages/auth/Login.jsx

Redirect the user to the home on loging instead of to the waiting page because it is not yet ready to be used.

Redirect the user to the home on loging.

---

docs/SummaryMetrics.md
src/js/pages/pipeline/Pipeline.jsx

In order to count releases for the given date interval, repos and devs, they're counted the distinct number of `release_url` of all the PRs returned for the same date interval, repos and devs, where `pr.release_url` is the URL of the earliest release that includes the PR.

Count releases

---

src/js/Routes.jsx
src/js/pages/prototypes/Tooltips.jsx
src/js/pages/prototypes/tooltip-info/TooltipInfo.jsx
src/sass/base/_typography.scss
src/sass/components/_tooltips.scss

This PR is related to the issue [#ENG-306](https://athenianco.atlassian.net/browse/ENG-306). It adds a static page with all the layouts and examples of the chart tooltips, adding the necessary styles. It can be reviewed here: http://localhost:3000/tooltips
- Main page:
- User tooltip:
- Text and numbers:
- Pull requests:
- Repositories:
- Releases:

Adding tooltips style guide for the charts

---

src/js/components/ui/filters/DateInterval.jsx
src/sass/components/_buttons.scss

caused by https://github.com/athenianco/athenian-webapp/pull/135#issuecomment-602519292
required by [[ENG-355]]
This PR adds the proper behavior to the already existent `close` and `apply` data filter buttons; the behavior agreed with @warenlg is:
- click outside -> (keep current behavior) if the filter is valid, apply; otherwise, avoid closing.
- click in cancel -> closes the filter without applying any change.
- click in apply -> (enabled only if the filter is valid) applies the new filter.
If the filter is not valid (startDate and endDate are not both valid), the `apply` button is disabled as shown below:
[ENG-355]: https://athenianco.atlassian.net/browse/ENG-355

Implement accept/cancel buttons in the date filter

---

package.json
src/js/components/insights/Box.jsx
src/js/components/insights/Helper.jsx
src/js/components/insights/Insights.jsx
src/js/components/insights/KPI.jsx
src/js/components/insights/charts/library/HorizontalBarChart.jsx
src/js/components/insights/stages/WorkInProgress.jsx
src/js/components/pipeline/StageMetrics.jsx
src/js/pages/pipeline/Stage.jsx
yarn.lock

Closes [ENG-371](https://athenianco.atlassian.net/browse/ENG-371).
This PR provides a framework for adding different charts for the insights sections of each stage. This framework lets the charts being defined in a declarative way where it's possible to define how data are calculated and how are displayed.
As the first chart to test this scaffolding, the "Most Active Developers" chart for the "Work In Progress" has been implemented.
All the work of this PR is confined in `js/components/insights`. Everything done outside is just to attach the insights sections to the webapp: [0f13e72](https://github.com/athenianco/athenian-webapp/commits?author=se7entyse7en).
`lodash` has ben used to make data plumbing easier and smoother since it provides a good set of data manipulation functions and the …

Add "Most Active Developers" insight chart with initial scaffolding

---

src/sass/components/_tables.scss

This PR is related to the ticket [#ENG-409](https://athenianco.atlassian.net/browse/ENG-409) and it adds an underline hover effect to the PR links on the tables.

Adding a hover effect to the PR links

---

package.json

The webapp will still be compiled as a `node:13.7-alpine` container,
and tests will run in Travis under `node v13 engine.

Let the user to decide for any node >= v12

---

src/js/components/pipeline/PullRequests.jsx
src/js/pages/pipeline/Pipeline.jsx
src/js/services/api/index.js
src/js/services/prHelpers.js

solves [[ENG-382]] Add the PRs stage-complete in each of the 4 tables
solves [[ENG-381]] Age of opened PRs should be `now()-pr.created`
- d205a27 solves [[ENG-382]] Add stage-complete into PR tables
- 2a2cf20 solves [[ENG-381]] Enhance Age in PR tables (if the PR has not `closed` date, it assumes `now()`)
- 768f2d4 Enhance filter and sort in PR tables
You can now filter by `status:<opened|merged|closed>`, `number:<PR-number>`, `author:<user>`, `participant:<user>`
- 182a429 Show PR Events and PR Completed Stages. It will be removed once [[ENG-325]] is released; in the meanwhile, it helps to understand why each PR is listed in each stage, showing events and complete stages.
[ENG-382]: https://athenianco.atlassian.net/browse/ENG-382
[ENG-381]: https://athenianco.atlassian.net/browse/ENG-381 …

Enhance PR tables

---

src/sass/components/_pipeline.scss

This is related to the ticket [#ENG-440](https://athenianco.atlassian.net/browse/ENG-440).
It adds a colored border to the hover of the pipeline tabs.

Adding hover effect to the pipeline tabs

---

src/js/components/pipeline/PullRequests.jsx
src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/Stage.jsx
src/js/services/prHelpers.js
src/sass/components/_tables.scss

solves [[ENG-325]] Label the PRs in each table
As described in the issue discussion, if a PR contains any comment, it will be labeled as `Changes Requested`
Also, if the mouse hovers the PR label, it will appear a tooltip containing the PR stage, events received and completed stages as in the screenshot below.
[ENG-325]: https://athenianco.atlassian.net/browse/ENG-325

Use stage labels instead of pr stages

---

src/js/components/insights/charts/library/BubbleChart.jsx
src/js/components/insights/stages/review/reviewActivity.jsx

Closes [ENG-360](https://athenianco.atlassian.net/browse/ENG-360).
At first render the charts are empty because the API call needs the list of contributors. This list is retrieved only on filter change, so you can see the chart by for example changing the date interval. This will be fixed automatically once the contributors' filter will be populated.
This PR already refactors a big amount of code for the `BubbleChart` component, though it can still be improved, at this point is enough already.

Review activity bubble chart

---

src/sass/components/_tabs.scss

This is based on the task [#ENG-457](https://athenianco.atlassian.net/browse/ENG-457) and adds a subtle border to the tabs on hover.

Adding simple hover effect to the tabs

---

src/js/components/charts/Tooltip.jsx
src/js/components/insights/charts/library/BubbleChart.jsx
src/js/components/insights/charts/library/HorizontalBarChart.jsx
src/js/components/insights/charts/library/TimeSeries.jsx
src/js/components/insights/charts/library/VerticalBarChart.jsx

Attach logic for tooltips to each visualization type by default. The style and the content of the tooltips is out of the scope of this PR. Now we show everything in the datapoint.

Insights charts tooltips

---

src/js/components/pipeline/MainMetrics.jsx
src/js/components/pipeline/StageMetrics.jsx
src/js/components/pipeline/Thumbnails.jsx
src/js/components/ui/Badge.jsx

- 128d75b [[ENG-321]] Configure positive/negative variation
- 5e75de4 [[ENG-376]] Omit variation badge if it's zero
Main change:
It can be selected the meaning of the variation, being good  (green) if less or greater than `0`
- `<Badge value={3} />` &rarr; regular badge, no variation
- `<Badge value={3} trend />` &rarr; variation badge (default), positive is good (green)
- `<Badge value={3} trend={POSITIVE_IS_BETTER} />` &rarr; variation badge, positive is good (green)
- `<Badge value={3} trend={NEGATIVE_IS_BETTER} />` &rarr; variation badge, positive is bad (red)
[ENG-321]: https://athenianco.atlassian.net/browse/ENG-321
[ENG-376]: https://athenianco.atlassian.net/browse/ENG-376

Enhance badges

---

src/js/components/insights/Insights.jsx
src/js/components/insights/charts/library/BubbleChart.jsx
src/js/context/Filters.jsx
src/js/hooks.jsx
src/js/pages/pipeline/Filters.jsx
src/js/pages/pipeline/Stage.jsx

Closes [ENG-463](https://athenianco.atlassian.net/browse/ENG-463).
This PR refactors the `Filters` component in order to have a cleaner handling of the state changes and to expose with the `FilterContext` a proper `ready` props. That `ready` props is then used by `Stage` component to avoid triggering API calls if filters are not ready.
This PR also adds proper state management for the data of the insights chart for each stage. Those data are refreshed with an API call only if filters change or if no data has been stored yet.
The `Insights` component now is aware of whether the data are being loaded, this makes possible to show a loading message or to improve it later using a spinner.
The `Stage` component could be simplified in the future, in particular, wrt the callback of the …

Rendering improvements and stabilization

---

src/js/components/pipeline/PullRequests.jsx

When clicking in the header of the second column of the PRs table (`PullRequest|Created`), the PRs will be sorted by  its `created` date

Let 'PullRequest|Created' 2nd column sort by 'pr.created' date

---

src/js/components/insights/KPI.jsx
src/js/components/insights/stages/review/waitTimeFirstReview.jsx

required by [[ENG-433]]
`Average Waiting Time for 1st review` and `Proportion of the Cycle Time` KPIs of `Wait Time for 1st Review` chart, seems to be good when decreasing, and bad if increasing, so this PR changes badge color following that rule.
[ENG-433]: https://athenianco.atlassian.net/browse/ENG-433

Fix variation 1st review kpi

---

src/js/components/pipeline/Thumbnails.jsx
src/js/pages/pipeline/Pipeline.jsx

closes [[ENG-405]]
Badges in pipeline thumbs will count `stage-complete` PRs instead of those PRs in `stage`
[ENG-405]: https://athenianco.atlassian.net/browse/ENG-405

Count stage-completed in pipeline thumbs badges

---

src/js/components/pipeline/PullRequests.jsx
src/js/services/prHelpers.js
src/sass/components/_badges.scss

required by [[ENG-456]]
_This PR does not introduce any visual change_
This PR prepares the PR labels to use their own colors. To do so, it will be only needed [to define css colors](https://github.com/athenianco/athenian-webapp/blob/master/src/sass/_variables.scss#L31) and to assign them [to the new label classes](https://github.com/athenianco/athenian-webapp/pull/178/files#diff-4f09eb729340b6778e426ca7f56d64fdR68).
[ENG-456]: https://athenianco.atlassian.net/browse/ENG-456

Prepare labels to use their own colors

---

src/js/components/charts/FilledAreaChart.jsx
src/js/components/charts/Tooltip.jsx
src/js/components/insights/charts/library/TimeSeries.jsx
src/js/components/insights/stages/review/waitTimeFirstReview.jsx
src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx

required by [[ENG-461]]
The new `One date with time` tooltip can act as:
- One date with time
- One date, time and pull requests
- PR Ratio Flow
To be used in:
- Summary metrics,
- Pull Request Ratio Flow,
- Wait Time for 1st Review
[ENG-461]: https://athenianco.atlassian.net/browse/ENG-461

Implement 'One date with time' tooltip

---

src/js/components/insights/charts/library/HorizontalBarChart.jsx
src/sass/components/_charts.scss
src/sass/main.scss

`react-vis` does not support the native `<Hint>` for axis, so it was implemented, as a workaround, a text label next to the user image.
- If it is approved, it should be styled using SVG native elements to match our design for `User Icon` tooltip
- Alternative: investigate if it can be attached a javascript handler to `<svg:image:onHover>`, and use it to handle the `react-vis` `<Hint>` passing the `(x,y)` position of the triggered event.
To be used in `YAxis` of the following charts:
- Most Active Developer
- Review Activity :: ReviewComments/Reviews per reviewer

Implement 'User Icon' tooltip

---

src/js/components/charts/FilledAreaChart.jsx
src/js/components/insights/charts/library/TimeSeries.jsx
src/js/components/pipeline/SummaryChart.jsx
src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/Stage.jsx

Adds a smart granularity calculation for summary charts based on the following logic:
- <= 21 days => 'day'
- <= 90 days => 'week'
- else => 'month'
This PR also fixes the grid line by making it match with the x-axis labels.

Smart granularity

---

.travis.yml
Dockerfile

This PR makes tests and build run inside docker container itself:
- makes both and tests more reliable as they run exactly in the same environment
- makes CI more stable, for example, today Travis was failing continuously in downloading node 13 using nvm, this is not more required since everything is done inside containers.

CI tests in docker container

---

src/js/components/charts/FilledAreaChart.jsx
src/js/components/charts/Tooltip.jsx
src/js/components/insights/charts/library/BubbleChart.jsx
src/js/components/insights/charts/library/VerticalBarChart.jsx
src/js/components/insights/stages/review/pullRequestSize.jsx
src/js/pages/prototypes/Tooltips.jsx
src/js/services/format.js
src/js/services/prHelpers.js

required by [[ENG-461]]
Implement tooltips:
- `Regular Pull Request`
- `Pull Request waiting for Review`
- `Pull Request Reviewed`
To be used in:
- Pull Request Size, review chart
- c5bc0581b73b9926a38ae28b8db69d2365cdae3e Adds the tooltip
- d7e5856 Make `Total number of files waiting for review` KPI count files waiting for review, instead of counting all files (also already approved ones)
- 07d411e Fix grouping of Pull Request Size review chart
This Chart shows PRs in two groups: waiting for review or not.
Grouping criteria should be having `review_happened` or `approve_happened` or `changes_request_happened` or `merge_happened` or being `closed`.
But since the tooltip also needs to show the time waiting for being reviewed, and the events
above do not expose it, we can only differentiate …

Tooltip user icon

---

src/js/components/insights/stages/review/pullRequestSize.jsx
src/js/components/pipeline/PullRequests.jsx

`Pull Request Size` chart was missing the repo org name in its tooltip

Fix repo name representation. Add org name

---

src/js/components/pipeline/PullRequests.jsx

The alternative would be to add the `pr.number` after the title, but it will be not visible in many prs because their titles are cropped because they're too long. See example below:

Add pr.number in PRs tables

---

src/js/pages/pipeline/Pipeline.jsx
src/js/services/prHelpers.js

I checked these edits and the displayed charts and metrics are identical to the current staging.

Do not rely on pr.stage in PR filtering requests

---

src/js/components/pipeline/PipelineCardMiniChart.jsx
src/js/components/pipeline/SummaryChart.jsx

Closes [ENG-549](https://athenianco.atlassian.net/browse/ENG-549)
Then only queries using adjusted interval were summary chart and mini charts.

Removes adjusted interval from summary chart and pipeline mini chart

---

src/js/pages/pipeline/Pipeline.jsx

Filter must consider only those created after the filter.from, ignoring the filter.to,
which is already considered by the API

Fix Created PRs from WIP summary metrics

---

docs/SummaryMetrics.md
src/js/components/pipeline/PullRequests.jsx
src/js/pages/pipeline/Pipeline.jsx
src/js/services/prHelpers.js

79a53c2 Fix how Reviewed Review Summary Metric is calculated:
Since some kind of reviews are not counted in `pr.comments` or `pr.review_comments`, this PR will also count as reviewed those PRs having at least one of the following `pr.properties`: `review`, `approve` or `changes_request`.
- 9f53731 Update docs about WIP stage. date_to is already considered by the API …
- 8c72834 Enhance PRs stage column:
- Show tooltip in the whole button, not only when hovering the label text
- Sort by shown label

Fix how Reviewed Review Summary Metric is calculated

---

src/sass/components/_badges.scss

This is related to the issue [#ENG-576](https://athenianco.atlassian.net/browse/ENG-576).
It adds two new label colors for the **Not Reviewed** and **Review Ignored** PRs on the **Review** section.

New colors for skipped and ignored review PRs

---

src/js/components/pipeline/PullRequests.jsx
src/sass/components/_tables.scss

This is related to the issue #ENG-568 and it adds a new system to show the sort icons on the table columns to the right of the titles. 
It also removes the sorting from the first column and adds a new order by default, sorting them by creation date as required by @warenlg.

Fixing sort icon on table columns and order by creation date

---

src/js/pages/auth/Callback.jsx

Related to [ENG-338](https://athenianco.atlassian.net/browse/ENG-338). This prevents raising the error and consequently preventing the redirect. In the meantime, in case the link doesn't open, we'll provide the installation link "by hand".

Just ensures that no error is raised in case unable to open installation link

---

src/js/components/ui/filters/DateInterval.jsx

Otherwise `react-dates` returns the midday.

Fix start and enddate returned by date filter

---

src/sass/components/_tooltips.scss

This is related to the issues [#ENG-446](https://athenianco.atlassian.net/browse/ENG-446) and [#ENG-566](https://athenianco.atlassian.net/browse/ENG-566). 
It improves the styles of the text tooltips to make the background white to match the chart tooltips and to make the text larger for a better readability.

Improving the text tooltips

---

src/sass/components/_tables.scss

This is related to the issue [#ENG-508](https://athenianco.atlassian.net/browse/ENG-508) and it also includes the changes of #226 as were required to do this one.
It adds a hover effect on the table headers:

Hover effect on table headers

---

src/js/components/pipeline/MainMetrics.jsx
src/js/components/pipeline/Thumbnails.jsx
src/js/components/ui/Info.jsx
src/js/components/ui/Typography.jsx
src/sass/base/_typography.scss
src/sass/components/_tooltips.scss

This is related to the issue [#ENG-567](https://athenianco.atlassian.net/browse/ENG-567).
It fixes the icon misalignment on the main metrics tabs.

Fixing the info icon alignment

---

src/js/components/pipeline/StageMetrics.jsx
src/js/pages/pipeline/Pipeline.jsx

[[ENG-589]] Fix Overview in the breadcrumb menu
caused by https://github.com/athenianco/athenian-webapp/pull/228
---
[ENG-589]: https://athenianco.atlassian.net/browse/ENG-589

Title Overview Summary Metric as 'Lead Time'

---

src/js/ContextRoute.jsx
src/js/Routes.jsx

This PR fixes the bug that requires a manual reload of the page after registration.
The problem was that the `UserContext` was used also by the `/callback` route. The component corresponding to the `/callback` route was calling the endpoint for accepting the invitation and then redirecting to the home page. The problem is that since the `UserContext` was wrapping all the routes, the `userState` was not re-computed when redirecting to the home page, hence no accounts were associated and filters weren't working due to missing `account` parameter.

Fix user registration callback that requires refresh

---

src/js/components/insights/stages/review/pullRequestSize.jsx

Handle missing author in PR size insight chart

---

src/sass/base/_typography.scss
src/sass/components/_pagination.scss

This is related to the issue [#ENG-617](https://athenianco.atlassian.net/browse/ENG-617). It fixes the color of the login link and the tables pagination.

Fixing pagination and login color

---

src/js/pages/Waiting.jsx
src/js/pages/auth/Callback.jsx
src/js/pages/auth/Login.jsx
src/sass/components/_waiting.scss

solves [[ENG-338]] During registration callback, opening the Athenian GitHub app installation tab could raise an error
- Once the process of accepting an admin-invitation succeeds, it is noticed to the user that Athenian GitHub App page will be opened in a new tab
- In 5s, the new tab with App URL will be automatically opened and focused.
- It will be shown the waiting message if any of the following happens:
- https://github.com/apps/athenian-owl is automatically opened and focused with no issue,
- when the Athenian GitHub APP tab can not be opened or focused,
- the user manually clicks in the link of the Athenian GitHub app https://github.com/apps/athenian-owl,
This PR uses the prototyped waiting page as defined by https://github.com/athenianco/athenian-webapp/pull/245
- Nothing …

Enhance user flow experience

---

src/js/components/DataWidget.jsx
src/js/components/pipeline/PipelineCardMiniChart.jsx
src/js/components/pipeline/Thumbnails.jsx

This PR optimizes the calls made to render the mini-charts. Instead of doing 4 separate requests, this PR will now do a single one for all 4 metrics. Side effects:
- the whole row is loaded "at once", but with the skeleton already there
- even if on each filter change the spinner appears, there's still a glitch for the data on the left (the number and the badge variation) as those are data "injected" from outside and not requested by the mini-chart component. I'd rather address this separately as it's part of a bigger change since for now there's not way to know whether those data injected from outside the component are ready or not.
_*done at 5x speed locally_

Mini charts squash requests

---

src/js/components/insights/stages/review/reviewActivity.jsx
src/js/components/pipeline/PullRequests.jsx
src/js/pages/pipeline/Pipeline.jsx
src/js/services/prHelpers.js

required by [[ENG-489]]
different improvements:
- bc11c6b Ensure that AVG reviewed PRs per dev count does not count multiple reviews in the same PR
- 1786476 Consider 'Reviewed' a PR only when review, rejection or approval events are present. Closed PRs having these events should be also considered as reviewed.
- 4045bcc Reviewed PRs must count unique PRs instead of sum the reviews made per developer, which can be made over the same PR
Improvements that I needed while fixing inconsistencies between Summary Metrics and Review Activity KPIs
- 83030c9 Exclude authors from commenters or reviewers in PRs table
- 26c1e7e Show created date in a tooltip over 'created ago' text in PR tables …
[ENG-489]: https://athenianco.atlassian.net/browse/ENG-489

Consistency

---

src/js/components/DataWidget.jsx
src/js/components/insights/Insights.jsx
src/js/components/pipeline/MainMetrics.jsx
src/js/context/Data.jsx
src/js/context/PRs.jsx
src/js/hooks.jsx
src/js/pages/pipeline/Body.jsx
src/js/pages/pipeline/Filters.jsx
src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/PullRequests.jsx
src/js/pages/pipeline/Stage.jsx
src/js/services/api/index.js

This PR does the following:
- adds a proper way to handle global data through the `DataContext` provider and the `DataWidget`
- removes unnecessary query to previous filtered PRs
- changed a call to previous filtered PRs to previous filtered contribs
Locally for the overview page it reduced the number of requests from 17 to 15, and from 34s to 25s of loading: -26%.

Main metrics requests improvement

---

src/js/components/insights/stages/review/reviewActivity.jsx
src/js/pages/pipeline/Pipeline.jsx
src/js/services/prHelpers.js

caused by [[ENG-489]]
Remove not authored PRs (e.g from bots) from Summary Metrics and Review Activity metrics.
Unauthored PRs will still appear in PR tables.
[ENG-489]: https://athenianco.atlassian.net/browse/ENG-489

Remove not authored PRs from Summary Metrics and Reviews Activity metrics

---

src/js/pages/Settings.jsx

This is related to the issue #ENG-676. It adds a `text-truncate`class to the name and the email on the Settings page to avoid the text to overflow the space.

Adding text-truncate to the user and the email

---

src/js/components/insights/Insights.jsx

This fixes an error that could happen if global data takes more time than usual to load.

Fix readiness check for insights useEffect

---

src/js/components/insights/Insights.jsx

Closes [ENG-615](https://athenianco.atlassian.net/browse/ENG-615).
This puts the loading of the insights section into an `error` state instead of looping and DDoS-ing the API. This shouldn't ever happen, but just in case I just put a simple copy. @warenlg up to you if wanna change it or provide a visual.

Insights error handling

---

src/js/pages/Waiting.jsx
src/js/pages/auth/Callback.jsx
src/js/services/api/index.js

solves [[ENG-683]] and [[ENG-682]]
- 13ad58a Ensure that regular users go to Overview after accepting regular invitations
- 49c0584 Handle possible errors …
- When the GH App page can not be opened, and the user clicks in the link to open it,
the error message will disappear.
- GH App page will only be opened if the logged user is admin.
Also:
- 7723f8e Fix. Mark as an admin a user owning an account even when it does not have any reposet
[ENG-683]: https://athenianco.atlassian.net/browse/ENG-683
[ENG-682]: https://athenianco.atlassian.net/browse/ENG-682

Waiting regular users

---

src/js/services/prHelpers.js

Fix https://athenianco.atlassian.net/browse/ENG-709
For the same date interval (March 1st to March 31st) before,
After,

Fix PR labeling when no stage has been completed

---

src/js/components/ui/filters/DateInterval.jsx

caused by https://github.com/athenianco/athenian-webapp/pull/277
depends on https://github.com/athenianco/athenian-webapp/pull/285
Only this commit : c324bc8f880730acce2ce3ce793d626204e535a2
Open the calendar pointing to the active filter instead of today.
https://www.loom.com/share/26a51d9fb33c45419a4d0dc8e9cad0cf

Fix datefilter

---

src/js/components/insights/charts/library/HorizontalBarChart.jsx
src/js/components/insights/stages/review/reviewActivity.jsx

https://athenianco.atlassian.net/browse/ENG-733
Before,
After,
In particular, with this PR, the chart has the same height as the **Pull Requests Authors** chart in the WIP section, for a given number of users displayed in the y-axis

Fix the height of the horizontal bar charts

---

src/js/services/prHelpers.js
src/sass/_variables.scss
src/sass/components/_badges.scss

https://athenianco.atlassian.net/browse/ENG-731
Many of the QR PRs are reviewed but still labeled as Waiting for Review similarly as for https://github.com/athenianco/athenian-webapp/pull/109 because we don't cover the case of a commented review (neither approval nor changes requested).
From now, they will be labeled as, **Review Submitted**.

Add the Review Submitted PR label

---

src/js/Routes.jsx

@warenlg, @eiso and I suffer every day: we use the god mode on prod heavily and often change accounts. It is VERY annoying for us to go to the developer tools every time we need an updated Bearer token. The previous assumption that we don't need `/bearer` on prod is completely destroyed, just as I expected.
Please merge this ASAP.

Enable /bearer on prod

---

src/js/Routes.jsx
src/js/components/layout/Navbar.jsx
src/js/context/User.jsx
src/js/hooks.jsx
src/js/pages/Settings.jsx
src/js/pages/Waiting.jsx
src/js/pages/auth/Callback.jsx
src/js/pages/auth/Login.jsx
src/js/pages/auth/SignUp.jsx
src/js/pages/pipeline/Filters.jsx
src/js/pages/prototypes/ReleaseSettings.jsx
src/js/pages/templates/Page.jsx
src/js/services/api/index.js
src/js/smart-components/InvitationCreator.jsx

Admins onboards will still redirect to waiting page, but it will still be possible to go to home page even without data ready until we don't fully implement progress polling.
- Better error handling during invitation creation
- New `/signup` route for invitations with update in copies
- Admin account is prioritized in case of multiple accounts
- Authenticaed users without an Athenian account are not allowed
- No more automatic logout in any case
- Disabled showing member invitation link in waiting page
- Styled logout button the same way the login one is
- Admin link without error: https://streamable.com/r2v3ra
- Admin link with error: https://streamable.com/vg89ia
- Login without account: https://streamable.com/f4c5iv
- Normal member link without error: https://streamable.com/y0077b
- …

User no account not allowed

---

src/js/components/DataWidget.jsx
src/js/components/pipeline/MainMetrics.jsx
src/js/components/pipeline/PullRequests.jsx
src/js/components/pipeline/StageMetrics.jsx
src/js/components/pipeline/Thumbnails.jsx
src/js/components/ui/Spinner.jsx
src/js/pages/pipeline/Body.jsx
src/js/pages/pipeline/Overview.jsx
src/js/pages/pipeline/Stage.jsx
src/js/res/palette.js

fix [[ENG-584]], [[ENG-585]] and [[ENG-719]]
Recognize different possible statuses in components and show them in the StatusIndicator.
If there are no repos available for the given filters, it hides the rest of the Pipeline Body as in the following screenshot:
[ENG-584]: https://athenianco.atlassian.net/browse/ENG-584
[ENG-585]: https://athenianco.atlassian.net/browse/ENG-585
[ENG-719]: https://athenianco.atlassian.net/browse/ENG-719

Move component status into the StatusIndicator

---

src/js/Routes.jsx
src/js/pages/Settings.jsx
src/js/pages/prototypes/ReleaseSettings.jsx
src/js/pages/prototypes/TeamsSettings.jsx
src/sass/components/_accordions.scss
src/sass/components/_dropdowns.scss
src/sass/components/_forms.scss
src/sass/components/_tables.scss

This is based on the issue [#ENG-727](https://athenianco.atlassian.net/browse/ENG-727) and on the latest changes on the `Settings` InVision prototypes [available here](https://zurinegrn558160.invisionapp.com/console/Athenian---Dashboard-ck6gn9es0003g01ab2k2y2k3p/ck9l8vlhl00dr014djfel0kk4/play).
I created a new prototype for the Teams settings page:
Notice that the `Add user` dropdown is not there as it is supposed to use [the same one](https://zurinegrn558160.invisionapp.com/console/Athenian---Dashboard-ck6gn9es0003g01ab2k2y2k3p/ck9l9hb5n00720117uohe345k/play) that we still have pending on the filters.

Adding Teams settings prototype page and minor changes on settings pages

---

src/js/pages/pipeline/Filters.jsx
src/js/services/api/index.js

Closes: https://athenianco.atlassian.net/browse/ENG-687
Only show the extra name if login and name are differente. example attached: dependabot-preview does not have an extra name since it'll be dependabot-preview (dependabot-preview)

feat(ENG-687): Add developer names to filter

---

src/js/components/charts/FilledAreaChart.jsx

fix(ENG-551): Fix cropping label on X Axis of chart

---

.travis.yml
Dockerfile

~3mins instead of the current (almost) ~6mins
- Test and build in the same stage, sequentially.
- Avoid building a new docker intermediate image just to build, and do it from dev intermediate image.

Speedup Travis

---

src/js/services/api/index.js
src/js/services/logger.jsx

Errors returned by the API, contains their details under error.body
Errors caused while parsing the response (e.g. JSON decode errors), are under err.error
Plain errors are also stringed with its original cause, if it exists
Strings and numbers are left untouched

Read API errors

---

src/js/components/layout/Navbar.jsx
src/js/pages/Settings.jsx

This PR will enable the link to `Settings` in the user menu, and hide the `Teams` link in the Settings aside in Production.
https://app.athenian.co/settings/team route will still be accessible by direct url.

Enable 'Settings' in user menu. Hide 'Teams' menu

---

src/js/components/development/index.jsx

`Development.isDev` returns `true` only if running with webpack server
`Development.isNotProd` returns `true` only if `process.env.NODE_ENV` is set to `development` or `staging` (e.g. through `public/config.js`)

Flags to detect development or not Prod

---

src/js/components/development/index.jsx
src/js/components/development/index.scss
src/js/components/insights/KPI.jsx
src/js/components/layout/Tabs.jsx
src/js/components/pipeline/MainMetrics.jsx
src/js/components/pipeline/Thumbnails.jsx
src/js/components/ui/Badge.jsx
src/js/components/ui/Typography.jsx
src/js/services/format.js
src/sass/base/_typography.scss
src/sass/components/_badges.scss

addresses [[ENG-477]] Remove the diff badges when there is no data to compare  
addresses [[ENG-481]] NaN in the "Proportion of the cycle time"
addresses [[ENG-779]] Fix the NAN and style the tooltip of the Lead Time distribution chart
`Badge` component is now responsible for rendering the badge if it received a number (or also string if it is not in `trend` mode). If it received a `NaN` or a `+-Infinite` it will send it as an error to Sentry because it will mean that a division by zero, or a wrong division happened.
You can see below the before, and after (in not Prod env; if it would be rendered in Prod, the error highlight won't be visible)
Also, **when it is not in Production**, such `NaN` or a `+-Infinite` errors will be highlighted as in the following screenshot, letting the …

Handle empty badges

---

src/js/App.jsx
src/js/components/insights/KPI.jsx
src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
src/js/components/ui/Badge.jsx
src/js/services/prHelpers.js
src/js/smart-components/ErrorBoundary.jsx

fix [[ENG-844]] Metric computational errors displayed as yellow badges in the UI
In order to catch Render stack traces, it is needed to use an [Error Boundary](https://reactjs.org/docs/error-boundaries.html) as done in 566fe6c
Some errors were thrown because `<SimpleKPI>` tries to render a variation `<Badge>` no matter it exists or not. Fixed by f009318 
- ff429a0 Add developer id to sentry log as done in API
- 91bc364 This commit emulates an error in `<Badge>` for Sentry, which will be deleted by https://github.com/athenianco/athenian-webapp/pull/337 once confirmed it's properly handled by Sentry.
[ENG-844]: https://athenianco.atlassian.net/browse/ENG-844

Handle badge errors

---

src/js/components/pipeline/PullRequests.jsx

fix [[ENG-888]] Allow to search PRs by repo name in the tables
caused by https://github.com/athenianco/athenian-webapp/pull/344
[ENG-888]: https://athenianco.atlassian.net/browse/ENG-888

Let the user filter by repo name

---

src/js/components/insights/charts/library/TimeSeries.jsx
src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
src/js/pages/pipeline/Body.jsx

fix [[ENG-898]] Finalize the PR ratio flow fix on the Frontend
partially addresses [[ENG-537]] Ignore points for days of the charts when we don't have data
null values were also removed :point_down: 
before this PR :point_down: 
[ENG-898]: https://athenianco.atlassian.net/browse/ENG-898
[ENG-537]: https://athenianco.atlassian.net/browse/ENG-537

Ratio flow

---

src/js/pages/settings/Releases.jsx

solves [[ENG-901]] Reset the branch and tag patterns when you select “Automatic“ in the release settings.
When the user selects the `Automatic` strategy, whatever patterns were used for tags and branches are restored to its default values.
[ENG-901]: https://athenianco.atlassian.net/browse/ENG-901

Restore default Branch and Tag patterns when using Automatic strategy

---

src/js/App.jsx
src/js/pages/settings/Releases.jsx
src/js/services/logger.jsx
src/sass/components/_alerts.scss

This is based on the issue [#ENG-838](https://athenianco.atlassian.net/browse/ENG-838), and it adds new styles and behavior for the `Toastify` alerts and a new copy for the success cases to simplify the messaging. 
It is still missing the new copy for the errors as it had several conditions that I wasn't sure about.

New alert styling and copy

---

src/js/components/charts/CleanAreaChart.jsx
src/js/components/charts/Tooltip.jsx
src/js/components/insights/charts/library/TimeSeries.jsx
src/js/components/insights/stages/review/waitTimeFirstReview.jsx
src/js/components/pipeline/StageMetrics.jsx
src/js/services/format.js

closes [[ENG-537]] Ignore points for days of the charts when we don't have data
Remove null values from Thumbnails and WaitTime1stReview
This PR also:
- 1dd15dc Let `dateTime.human` return decimals when rounding times
- 6e5c388 Make `TimeSeries` chart to work also with time durations in `y-axis`, just passing `timeMode={true}` property. This will avoid us to make conventions between time durations and best unit outside the chart, because that conversion will be done inside the `TimeSeries` chart.
[ENG-537]: https://athenianco.atlassian.net/browse/ENG-537

Remove null values from Thumbnails and WaitTime1stReview

---

src/js/components/insights/stages/review/pullRequestSize.jsx
src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx

addresses [[ENG-903]] Exclude PRs not having the reviewing property from the PR size chart
As explained in the issue desc, we still not know when a PR was reviewed, so PullRequestSize chart is still about **approved** vs **not approved** PRs and the time **waiting for approval**:
- Approved PRs (green)
&rarr; the tooltip shows `(approved || merged) - (review_requested || created)`
- Not Approved PRs (orange)
&rarr; the tooltip shows `now() - (review_requested || created)`
see source code:
```js
// green if in MERGE, RELEASE or DONE; orange if still in REVIEW (not yet approved)
const reviewed = pr.completedStages.includes(PR_STAGE.REVIEW);
// tooltip
const timeWaiting = dateTime.interval(
pr.review_requested || pr.created,
pr.approved || endTime
);
```
[ENG-903]: …

Exclude WIP PRs from PullRequestSize chart

---

src/js/pages/settings/Team.jsx
src/sass/components/_dropdowns.scss
src/sass/components/_forms.scss

This fixes the issue [#ENG-956](https://athenianco.atlassian.net/browse/ENG-956). It fix the search box height on the 'Add new team' dropdown. I also added some minor style fixes on the dropdown:

Fixing the search box on the Add new team dropdown

---

src/js/components/ui/filters/MultiSelect/CustomStyles.jsx
src/js/pages/settings/Team.jsx
src/sass/components/_datepicker.scss
src/sass/components/_filters.scss

This is related to the issue #ENG-958 and it adds some styling to the filters to make them consistent:
- Make the border color of the dev and repo filter on hover lighter (same color as the status filter on hover)
- Add the border color change on hover over the daterange picker box
- Style the `:active` state on the filters
- Make the :focus on the search boxes consistent with the rest of the webapp inputs

Improving filters consistency and styles

---

src/sass/base/_typography.scss

This fixes the issue [#ENG-969](https://athenianco.atlassian.net/browse/ENG-963). If fixes the size of the main summary metrics on the pipeline charts to match the prototypes:

Fix main summary metric size

---

src/js/pages/settings/Team.jsx

Closes: https://athenianco.atlassian.net/browse/ENG-972
If we create a team in a different order the button stays disabled.
- Pick team members first then add a team name, it'll keep the button disabled

fix(ENG-972): Add New Team button disabled even with teamName and teamMember

---

src/js/components/insights/charts/library/VerticalBarChart.jsx
src/js/components/insights/stages/review/pullRequestSize.jsx
src/js/components/insights/stages/work-in-progress/createdPrs.jsx

required by [[ENG-761]]WIP: Pull Requests created through time
- Use the new chart title and definition,
- Change the 2nd KPI to be the Total number of PRs,
- Set the chart height to `300px`,
**TODO**
- Change the 1st chart KPI to be the average over working days, which is pending of confirmation.
[ENG-761]: https://athenianco.atlassian.net/browse/ENG-761

Enhance Created Pull Requests WIP chart with new definitions

---

src/js/components/insights/stages/work-in-progress/createdPrs.jsx
src/js/components/layout/Footer.jsx
src/js/pages/Settings.jsx

fix [[ENG-761]] WIP: Pull Requests created through time
This will discard days when no PR was created when calculating the average
The Chart is still hidden at Prod; let me know if we should enable it, or feel free to PR it on your own.
[ENG-761]: https://athenianco.atlassian.net/browse/ENG-761

Use only active days for CreatedPRs chart average KPI

---

src/js/components/insights/stages/review/pullRequestSize.jsx
src/js/services/prHelpers.js

solves [[ENG-938]] PR Size chart not seeing approval event from the future
solves [[ENG-942]] Remove the approx of the PR Size chart relying on the approval instead of the 1st review
Use `first_review` new PR property to calculate the time between `review_requested` or `created` event and that time.
Also, this PR stops converting PR date properties into `Date` types because it's already done by OpenApi client generator (see d2066f4)
[ENG-938]: https://athenianco.atlassian.net/browse/ENG-938
[ENG-942]: https://athenianco.atlassian.net/browse/ENG-942

Pr size improvements

---

src/js/components/insights/charts/library/HorizontalBarChart.jsx

[[ENG-836 ]] Fix the height of the horizontal bar chart in the Review section when showing few devs
default
with 4 developers
with 3 developers
with 2 developers
with 1 developer

Fix Horizontal Bar chart height depending in its content

---

src/js/components/ui/filters/MultiSelect/CustomComponents.jsx
src/js/components/ui/filters/MultiSelect/index.jsx
src/js/pages/pipeline/Filters/index.jsx

Closes: https://athenianco.atlassian.net/browse/ENG-887
how to test:
1) Open any filter repo/users
2) Click an option
3) Open users group, scroll and click an option
Expected result:
No more scrolling to the top or collapsing Groups

fix(ENG-887): Avoid going back to top when clicking on a filter option

---

src/js/components/insights/stages/work-in-progress/index.jsx
src/js/services/prHelpers.js

Addresses [[ENG-761]] [new chart] WIP: Pull Requests created through time
Required by https://github.com/athenianco/athenian-webapp/pull/386#issuecomment-635923470
This will show Created PRs chart into Production
[ENG-761]: https://athenianco.atlassian.net/browse/ENG-761

Enable Created PRs chart in prod

---

package.json
src/js/components/charts/Tooltip.jsx
src/js/components/pipeline/PullRequests.jsx
src/js/components/pipeline/StageMetrics.jsx
src/js/components/pipeline/Thumbnails.jsx
src/js/components/ui/Info.jsx
src/sass/components/_pipeline.scss
src/sass/components/_tooltips.scss
yarn.lock

required by [[DEV-90]] Remove usage of jQuery from webapp
This replaces jQuery tooltips in react components in order to use [`react-tooltip`](https://wwayne.github.io/react-tooltip/) instead.
PR table using `datatables.net` is not a React component, so its tooltips are still jQuery version. 
[DEV-90]: https://athenianco.atlassian.net/browse/DEV-90

Use react-tooltips

---

src/js/components/insights/stages/work-in-progress/index.jsx

This PR will hide the new Wip chart: **Pull Requests per Repo** from Prod till @warenlg validates it.

Hide Wip > Pull Requests per Repo from Prod

---

Makefile.testenv

Fix creation of instance id for QA env due to echo -n different implementations

---

src/js/components/ui/filters/MultiSelect/CustomComponents.jsx
src/js/components/ui/filters/MultiSelect/index.jsx
src/js/pages/pipeline/Filters/filterReducer.jsx
src/js/pages/pipeline/Filters/index.jsx

Closes: https://athenianco.atlassian.net/browse/ENG-973
Closes: https://athenianco.atlassian.net/browse/ENG-979
Makes a developers selection independent from each other, e.g.: If a developer is in "Core team" and also in "Front-end team" we can deselect this developer from one team and not the other.

fix(ENG-979/ENG-973): Make the dev selection independent in the dev filter

---

src/js/context/User.jsx
src/js/pages/settings/Profile.jsx
src/js/services/api/index.js
src/sass/components/_forms.scss

https://www.loom.com/share/7511504010a3465a81c9048a3d659371
Current API does not expose God capacities under `/user` endpoint, so it's checked directly from the Admin section directly trying to use it. If the user can not use it, the whole admin section is hidden from the Profile page.
It would be better if the God capacities are directly exposed by `/user` endpoint.

Let God Users to impersonate other users from their Profile settings page

---

src/js/components/DataWidget.jsx
src/js/pages/pipeline/Body.jsx
src/js/pages/pipeline/Stage.jsx
src/js/services/api/index.js

caused by [[DEV-203]], as described by [DEV-203#13049](https://athenianco.atlassian.net/browse/DEV-203?focusedCommentId=13049)
If the API fails, instead of neverending spinners it will be shown a proper error message.
Each `<DataWidget>` component trying to use some data from the API will show an error message if its data could not be retrieved
In the following screenshot, the API was forced to return a `403 Error` for all `/filter/pull_requests` and `/metrics/prs`; that's because user image and filters loaded, but the rest of the components relying on the failing endpoints show an error.
[DEV-203]: https://athenianco.atlassian.net/browse/DEV-203

Show error message when a component could not fetch data.

---

public/index.html

This is related to the issue [#DEV-213](https://athenianco.atlassian.net/browse/DEV-213). It adds the open graph meta tags to display the proper information when sharing the webapp.

Adding open graph meta tags

---

public/index.html

This solves the issue [#DEV-212](https://athenianco.atlassian.net/browse/DEV-212). 
I changed the viewport `initial-scale` to `0.1` to display the whole `webapp` on mobile without the breaking points. This is a temporary solution until we decide how to proceed with mobile screens properly.

Changing viewport to make it more usable on mobile

---

src/js/components/DataWidget.jsx
src/js/components/insights/Box.jsx
src/js/components/insights/charts/library/TimeSeries.jsx
src/js/components/insights/stages/merge/abandonedWork.jsx
src/js/components/insights/stages/merge/mergeDelays.jsx
src/js/components/insights/stages/review/pullRequestSize.jsx
src/js/components/insights/stages/review/reviewActivity.jsx
src/js/components/insights/stages/review/waitTimeFirstReview.jsx
src/js/components/insights/stages/work-in-progress/createdPrs.jsx
src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
src/js/components/layout/Empty.jsx
src/js/components/pipeline/StageMetrics.jsx
src/sass/components/_charts.scss

required by [[DEV-189]] Display an informative visual when no data is available for the summary charts
-----
**note**: `insight` represents a single block of the webapp containing a chart and some optional data (KPIs and such), which is a candidate to be considered "Empty" under certain circumstances.
-----
Each `insight` is compounded of many pieces of information (KPIs, chart data, averages...), so there may be no a single way to define **WHEN** an `insight` must be considered "empty", nor **HOW** to show the "Empty" message; thus, each `insight` must provide its logic to be considered "empty".
For this initial iteration:
- an `insight` will be considered as "empty" **WHEN** there is no data to be plotted in the chart &mdash;no matter the rest of the info&mdash;.
- the way **HOW** an …

"Empty" message when there is no data for an insight

---

src/js/pages/pipeline/Filters/index.jsx

Fixes the date interval change not retriggering the api calls for refreshing the charts. The bug has been introduced [here](https://github.com/athenianco/athenian-webapp/pull/421/commits/177b5c5eb161a5e6e1798dab3a452749a6adddc1) in https://github.com/athenianco/athenian-webapp/pull/421.

Make date interval change re-trigger api calls for charts re-rendering

---

src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx

Closes: https://athenianco.atlassian.net/browse/DEV-125
It's very tricky to test:
- Go to WIP
- Scroll to Pull Request Ratio Flow
- hover the points as fast as possible, it'll cause a glitch showing a long numbers
this PR just makes sure to show a fixed integer.

fix(DEV-125): Strange hover behavior on PR ratio flow chart
