- MAINTAINERS
Adding myself as the web app maintainer
> Add dpordomingo as a maintainer of the web app

- .travis.yml
- docs/CONTRIBUTING.md
- package.json
- yarn.lock
Some enhancements and dependencies updates
- 58a4c4e Let the build work in different paths
- 21b21ff Update dependencies
- bb31380 Enhance docs
- 3c3b197 Enhance Travis
> Enhance docs and travis

- README.md
- package-lock.json
- package.json
- src/App.js
- src/components/charts/Example.jsx
- src/components/pipeline/Pipeline.js
- src/components/pipeline/PipelineBody.js
- src/components/pipeline/PipelineCard.js
- src/sass/main.scss
Closes [ENG-65](https://athenianco.atlassian.net/browse/ENG-65?atlOrigin=eyJpIjoiMzYxMTY0ODIwZjhlNGExMTk0OTQ5Y2RkYmQ3NzE3Y2YiLCJwIjoiaiJ9).
> Adds tabs logic on mini-timeseries

- Makefile
according to https://github.com/athenianco/ci/pull/1 it will be mandatory
> Makefile -> add PROJECT variable

- src/components/charts/CleanAreaChart.js
- src/components/pipeline/PipelineCard.js
Closes [ENG-79](https://athenianco.atlassian.net/browse/ENG-79).
> Reusable clean area chart

- src/App.js
- src/components/base/Card.js
- src/components/charts/ExampleCustomized.jsx
- src/components/pipeline/PipelineBody.js
- src/components/pipeline/PipelineCard.js
Closes [ENG-92](https://athenianco.atlassian.net/browse/ENG-92).
> Pipeline body layout

- .travis.yml
have to merge https://github.com/athenianco/ci/pull/3 first
> push tag latest

- package.json
- src/App.js
- src/components/charts/CleanAreaChart.js
- src/components/pipeline/Pipeline.js
- src/components/pipeline/PipelineCard.js
- src/sass/_overrides.scss
- src/sass/_typography.scss
- src/sass/_variables.scss
- src/sass/main.scss
- src/utils/colors.js
- yarn.lock
fix [[ENG-81]] Finalize the cards of the pipeline by adding the extra information
- 3a5384f45c90fac8d5a86c1c5ba7d279acd94320 Completes the pipeline thumbnails
- 0ed2f4b Fine tunning of the layout to fit the design, and create space in the thumbnails; And also some sass assets rearrangements.
- f8256b3 Use a fork of **SB Admin 2** which enables grid gutter config (see details at #22)
[ENG-81]: https://athenianco.atlassian.net/browse/ENG-81
> ENG-81 Complete the pipeline thumbnails

- src/js/Routes.test.js
- src/js/components/layout/Navbar.jsx
- src/js/pages/auth/Logout.jsx
- src/js/pages/templates/Page.jsx
caused by #32
Some minor improvements for the UX:
- Afther logging out, the user is redirected to the Home.
- If there is no user logged in, it won't be requested the user data to the API
> Improve auth UX

- package.json
> Fix homepage in package.json

- docs/CONTRIBUTING.md
- public/config.js
- src/js/pages/auth/Logout.jsx
> Make logout redirect uri configurable through config.js file

- src/index.js
- src/js/components/layout/Navbar.jsx
- src/js/components/ui/Info.jsx
- e605325 Fix toltip to be loaded on component mount
- b25a4b8 Add login icon <img src="https://user-images.githubusercontent.com/2437584/73346309-ef3c2000-4285-11ea-92cf-083439a7577a.png" width="70" />
> Add login icon and fix Info tooltip

- public/config.js
- src/js/App.jsx
This PR makes the token returned by Auth0 a JWT token as expected by the api.
> Add missing audience param

- src/js/PrivateRoute.jsx
> Remove console.log leftover

- public/config.js
- src/js/Routes.test.js
- src/js/services/api/index.js
> Make api url configurable

- package.json
- src/js/components/pipeline/TopFilter.jsx
- src/js/components/ui/AriaLabel.jsx
- src/js/services/api/index.js
- src/js/services/github.js
- src/sass/main.scss
- yarn.lock
depends on #52
This PR makes the filters work with data from the API (currently mocked data because the API does not expose this data; see [[ENG-153]])
Connect the filters to the rest of the App, so it will call the API according to the filter settings.
[ENG-153]: https://athenianco.atlassian.net/browse/ENG-153
> Add multi-select and date-time filters using API data

- docs/CONTRIBUTING.md
They're needed 2 different Apps:
- one for Athenian API,
- one for the SPA.
> Document how to locally run Athenian

- public/config.js
- src/js/pages/auth/Callback.jsx
> Trigger Github application installation in new tab

- .travis.yml
- Makefile
blocked by https://github.com/athenianco/ci/pull/4
> add required static field to be sent over pubsub

- src/js/Routes.jsx
- src/js/components/layout/Breadcrumbs.jsx
- src/js/context/Breadcrumbs.jsx
- src/js/pages/Home.jsx
- src/js/pages/Pipeline.jsx
- src/js/pages/pipeline/Overview.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/pages/templates/Page.jsx
- yarn.lock
blocks https://github.com/athenianco/athenian-webapp/pull/60
- eaeb80e Convert `/stage/:name` into a nested route of `/stage`
It will let Stage to preserve some parts untouched (not re-rendered) when navigating between overview and stages
- 8dec13c Add `useBreadcrumbsContext` hook to change the Breadcrumbs from Page parts
Page is wrapped inside a `BreadcrumbsContext` which stores a setter for
the Breadcrumbs to be used by Page parts through `useBreadcrumbsContext`.
> Enhance navigation

- src/js/Routes.jsx
- src/js/pages/prototypes/Prototypes.jsx
- src/js/pages/prototypes/types/BubbleChart.jsx
- src/js/pages/prototypes/types/HorizontalBarChart.jsx
- src/js/pages/prototypes/types/PositiveNegativeBarChart.jsx
- src/js/pages/prototypes/types/ScatterPlot.jsx
- src/js/pages/prototypes/types/VerticalBarChart.jsx
- src/js/res/palette.js
Prototypes for charts from [our Product Design Doc](https://docs.google.com/document/d/19uHBCKmqwYcysiIZodR_y37qxpG9nyP9GPpZmCGV3Pg).
Legends will be added separately, because `react-vis` is not that good letting you configure and place it properly.
> [RFC] Prototypes

- src/js/components/charts/CleanAreaChart.jsx
- src/js/components/charts/TimeSeries.jsx
- src/js/components/pipeline/Thumbnails.jsx
- src/js/components/ui/Badge.jsx
- src/js/components/ui/Typography.jsx
- src/js/services/api/index.js
- src/sass/main.scss
depends on https://github.com/athenianco/athenian-webapp/pull/60
depends on https://github.com/athenianco/athenian-webapp/pull/65
depends on https://github.com/athenianco/athenian-webapp/pull/66
depends on https://github.com/athenianco/athenian-webapp/pull/67
Some different enhancements to be reviewed per commit:
- f7e8f21 Enhance pipeline thumbnails
- 7a9cd2e Enhance minichart in thumbs
- 050e920 Remove unnecesary filters in the MetricsRequest
- 66f6fbc Add hints to the pipeline thumbnails
- fd31b92 Fix TimeSeries chart domains and axis
- 09f1592 Prepare Typography components to receive null values
> Enhancements

- src/js/components/pipeline/Thumbnails.jsx
- src/js/pages/pipeline/Body.jsx
depends on #60
depends on #65
depends on #66
depends on #67
depends on #68
depends on #69
changes are only introduced by 17ad96c
> Show PRs in each pipeline thumbnail

- src/js/components/pipeline/Thumbnails.jsx
- src/js/pages/pipeline/Body.jsx
- src/sass/_variables.scss
- src/sass/main.scss
depends on #60
depends on #65
depends on #66
depends on #67
depends on #68
depends on #69
depends on #70
The change is only done by 9cabc4a
when in `wip` stage.
when in `release` stage.
> Add new thumbnails active effect

- src/js/pages/pipeline/Body.jsx
as described by https://github.com/athenianco/athenian-webapp/pull/66#discussion_r383797231
> Make MainMetrics::PRs to count ALL PRs

- src/js/Routes.jsx
- src/js/components/development/index.jsx
- src/js/components/development/index.scss
Close #77
Alternative to #77. Follows https://github.com/athenianco/athenian-webapp/pull/77#issuecomment-590908969
However, it does not work and I cannot find the reason why.
> Add /bearer route to generate auth tokens

- src/js/components/pipeline/Thumbnails.jsx
- src/js/components/ui/Badge.jsx
- src/js/pages/pipeline/Body.jsx
- src/js/services/api/index.js
It will be called the api doubling the passed DateInterval.
Once the response is obtained, it will be calculated the variation between the previous period, and the passed DateInterval.
Once obtained the variation, it's returned the data only for the passed DateInterval.
> Calculate variation between current and prev period

- src/js/components/pipeline/Thumbnails.jsx
- src/js/res/palette.js
- src/sass/_overrides.scss
- src/sass/_variables.scss
- src/sass/main.scss
As requested on the issue #73 I included here the proper color variables and fixed the colors for the pipeline elements removing the previous active behavior and replacing it with css styles.
> Adding proper color variables and fixing the color backgrounds

- src/js/components/ui/Badge.jsx
- src/sass/_overrides.scss
- src/sass/components/_badges.scss
- src/sass/components/_tables.scss
- src/sass/main.scss
Based on the task [#ENG-268](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?selectedIssue=ENG-268), I fixed the badges styles to make them match the prototypes. Also some minor additional changes on styling were made in order to fix some color matching after minor overrides on color variables.
> Styling badges and minor additional style fixing

- src/js/components/pipeline/MainMetrics.jsx
- src/js/components/pipeline/Thumbnails.jsx
- src/js/components/pipeline/TopFilter.jsx
- src/sass/components/_pipeline.scss
This is related to the task [#ENG-271](https://athenianco.atlassian.net/jira/software/projects/ENG/boards/4?assignee=5e57d3bc459a810c9af2098b&selectedIssue=ENG-271).
It fixes and improves the pipeline area to match the prototypes:
- Border width on the timeline
- Padding adjustments on boxes
- Adding border bottom to the tabs
- Replacing the hover effect
- General margins and borders review
> Fixing margins, borders and other minor improvements on the pipeline

- src/js/components/pipeline/Thumbnails.jsx
- src/js/services/api/index.js
- src/js/services/format.js
Minor changes:
- 10696cd Tune human format
- 144109e Mark TODOs to avoid missing them:
- Stage PR count and Stage average must be obtained from the API to show stage-complete instead of stage-pending prs
> Minor fixes and adding TODOs

- src/js/components/layout/Breadcrumbs.jsx
- src/js/components/layout/Navbar.jsx
- src/js/components/pipeline/PullRequests.jsx
- src/sass/_overrides.scss
- src/sass/base/_typography.scss
- src/sass/components/_badges.scss
- src/sass/components/_dropdowns.scss
- src/sass/components/_forms.scss
- src/sass/components/_pagination.scss
- src/sass/components/_tables.scss
- src/sass/layout/_header.scss
- src/sass/main.scss
This PR is related to the issue [#ENG-278](https://athenianco.atlassian.net/browse/ENG-278?atlOrigin=eyJpIjoiMmE1NjljNDZlOGIwNGU5Mzg3ZDcwMDRkZmQ3MGE3MjciLCJwIjoiaiJ9). It also includes the commit of the pending PR #90 as it included some necessary styles for this one.
It fixes the pagination to add the proper styles:
> Adding pagination styles to match the prototypes

- src/js/components/pipeline/PullRequests.jsx
- src/sass/components/_tables.scss
This is related to the issue #ENG-289.
I added styles to the search field on the PRs table.
> Adding style to the search filter on the PRs table

- src/js/components/layout/Tabs.jsx
- src/js/components/pipeline/PullRequests.jsx
- src/js/components/pipeline/StageMetrics.jsx
- src/js/pages/pipeline/Overview.jsx
- src/js/pages/pipeline/Pipeline.jsx
- src/js/pages/pipeline/Stage.jsx
- src/sass/base/_utilities.scss
- src/sass/components/_tabs.scss
- src/sass/main.scss
This PR adds PRs tab into each stage
> Add PRs tabs into stages

- .travis.yml
related to [[ENG-275]]
[ENG-275]: https://athenianco.atlassian.net/browse/ENG-275
> ci -> deploy only on master push

- .travis.yml
based on [this](https://github.com/travis-ci/travis-ci/issues/6893#issuecomment-354967391) and [this](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) docs
fix [[ENG-375]]
[ENG-375]: https://athenianco.atlassian.net/browse/ENG-375
> travis -> push docker image with TRAVIS_TAG

- package.json
- src/js/components/ui/filters/DateInterval.jsx
- src/js/pages/pipeline/Filters.jsx
- src/sass/components/_datepicker.scss
- yarn.lock
closes [[ENG-355]]
This PR implements the DateInterval filter using `airbnb/react-dates`
[ENG-355]: https://athenianco.atlassian.net/browse/ENG-355
> Integrate DateInterval calendar using "react-dates"

- src/js/components/ui/filters/DateInterval.jsx
- src/sass/components/_buttons.scss
- src/sass/components/_datepicker.scss
- src/sass/main.scss
This is related to the issue [#ENG-397](https://athenianco.atlassian.net/browse/ENG-397). I added some style adjustments to make the date picker more close to the prototypes.
> Minor style adjustments to the date picker

- src/js/components/insights/Box.jsx
- src/js/components/insights/KPI.jsx
> Hotfix post-review

- package.json
- src/js/components/insights/Box.jsx
- src/js/components/insights/Helper.jsx
- src/js/components/insights/KPI.jsx
- src/js/components/insights/charts/library/BubbleChart.jsx
- src/js/components/insights/stages/Review.jsx
- src/js/components/insights/stages/WorkInProgress.jsx
- yarn.lock
> Add "Pull Request Size" insight chart

- src/js/components/insights/Helper.jsx
- src/js/components/insights/stages/Review.jsx
- src/js/components/insights/stages/WorkInProgress.jsx
- src/js/pages/pipeline/Stage.jsx
Depends on: #132, #136.
Refactors the code in order to let each chart be able to query their own data.
Only relevant commit: https://github.com/athenianco/athenian-webapp/pull/138/commits/bfaa5e838773abe96e454ea650bd10e2f47381e0
> Insights charts api call

- src/js/components/insights/Helper.jsx
- src/js/components/insights/charts/library/TimeSeries.jsx
- src/js/components/insights/stages/Review.jsx
- src/js/components/insights/stages/WorkInProgress.jsx
- src/js/pages/pipeline/Stage.jsx
Closes [ENG-358](https://athenianco.atlassian.net/browse/ENG-358).
Depends on: #132, #136, #138.
> Add "Wait time for 1st review" insight chart

- src/js/components/insights/charts/library/TimeSeries.jsx
- src/js/components/insights/stages/Review.jsx
- src/js/components/insights/stages/WorkInProgress.jsx
Closes [#362](https://athenianco.atlassian.net/browse/ENG-362).
Depends on: #132, #136, #138, #139.
> Add "Pull Request Ratio Flow" insight chart

- src/js/components/insights/Helper.jsx
- src/js/components/insights/charts/library/BubbleChart.jsx
- src/js/components/insights/charts/library/HorizontalBarChart.jsx
- src/js/components/insights/charts/library/TimeSeries.jsx
- src/js/components/insights/stages/Review.jsx
- src/js/components/insights/stages/WorkInProgress.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/services/api/index.js
Cleaned up things:
- make all API calls from `services/api`,
- remove warning related to insights charts,
- remove functions related to sample charts,
- found a way to properly inject `svg` tags required inside a react-vis plot. (This will be useful to refactor other components, but now now, probably once I'll deal with them again.)
> Some cleanup

- src/js/components/insights/Box.jsx
- src/js/components/insights/charts/library/HorizontalBarChart.jsx
- src/js/components/insights/stages/Review.jsx
- src/js/components/insights/stages/WorkInProgress.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/services/api/index.js
Closes [ENG-360](https://athenianco.atlassian.net/browse/ENG-360).
Missing images will be addressed seprately.
> Review activity chart

- src/js/components/pipeline/PullRequests.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/pages/prototypes/Tooltips.jsx
- src/js/services/api/index.js
> Remove warnings

- src/js/components/layout/Breadcrumbs.jsx
- src/js/context/Breadcrumbs.jsx
- src/js/pages/Pipeline.jsx
- src/js/pages/pipeline/Pipeline.jsx
- src/js/pages/templates/Page.jsx
Fixes broken rendering introduced by #151
> Fix Breadcrumb context level and rendering

- src/js/context/User.jsx
- src/js/pages/templates/Page.jsx
Hotfix for impossible login after #149.
> Fix broken login

- src/js/components/insights/stages/review/reviewActivity.jsx
> Add filtering of developers with no review activity

- src/js/components/insights/Helper.jsx
- src/js/components/insights/charts/library/VerticalBarChart.jsx
- src/js/components/insights/stages/merge/index.jsx
- src/js/components/insights/stages/merge/mergeDelays.jsx
Closes [ENG-363](https://athenianco.atlassian.net/browse/ENG-363).
> Merge delays

- src/js/components/pipeline/MainMetrics.jsx
- src/js/components/pipeline/PullRequests.jsx
- src/sass/components/_tables.scss
solves [[ENG-378]] [[ENG-442]]
- 8d374f0 [[ENG-378]] Rename 'participants' PRs column as 'reviewer'' …
- 23d17fa [[ENG-442]] Rename 'Pull Requests in progress' Main Metric as just 'Pull… …
[ENG-378]: https://athenianco.atlassian.net/browse/ENG-378
[ENG-442]: https://athenianco.atlassian.net/browse/ENG-442
[ENG-378]: https://athenianco.atlassian.net/browse/ENG-378
[ENG-442]: https://athenianco.atlassian.net/browse/ENG-442
> Some enhancements

- src/js/components/insights/stages/review/pullRequestSize.jsx
> Hotfix for non boolean response from api

- src/js/components/charts/FilledAreaChart.jsx
Adds basic overlay functionality. The styling is out of the scope of this PR.
> Add basic overlay functionality to FilledAreaChart

- src/js/components/charts/FilledAreaChart.jsx
- src/js/components/charts/Tooltip.jsx
Creates a `Tooltip` component. The styling is out of the scope of this PR.
> Tooltip component

- src/js/components/pipeline/MainMetrics.jsx
- src/js/pages/pipeline/Body.jsx
Required by [[ENG-441]]
It's using hardcoded data because of [[ENG-464]]
[ENG-441]: https://athenianco.atlassian.net/browse/ENG-441
[ENG-464]: https://athenianco.atlassian.net/browse/ENG-464
> Prepare Cycle Time Main Metric

- src/js/components/insights/stages/review/pullRequestSize.jsx
Fixes broken compatibility after api spec update in #166.
> Hotfix due to broken chart after api spec update

- src/js/components/pipeline/MainMetrics.jsx
- src/js/context/Pipeline.jsx
- src/js/pages/pipeline/Body.jsx
- src/js/pages/pipeline/Pipeline.jsx
- src/js/services/api/index.js
close [[ENG-464]] Add Cycle Time to the permanent metrics
todo:
- [[ENG-404]] Call the API to get the avg time in stage and MainMetrics
[ENG-464]: https://athenianco.atlassian.net/browse/ENG-464
[ENG-404]: https://athenianco.atlassian.net/browse/ENG-404
> Fetch CycleTime data from the API

- package.json
- src/js/components/insights/Insights.jsx
- src/js/components/ui/Spinner.jsx
- yarn.lock
Closes [ENG-436](https://athenianco.atlassian.net/browse/ENG-436).
The color used is the one of the logo.
> Add loading spinner for insights section

- docs/SummaryMetrics.md
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/pipeline/MainMetrics.jsx
This patch fixes:
- The text style of some visual components to lowercase
- The copy to ensure that is more readable for humans and less "developer" style.
- Small typo
NOJIRA
> Fix for typos and copy

- .gitignore
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/pages/pipeline/Overview.jsx
- src/js/pages/pipeline/Pipeline.jsx
- src/sass/components/_pipeline.scss
closes [[ENG-474]] Stages proportional time should be over CycleTime instead of LeadTime
[ENG-474]: https://athenianco.atlassian.net/browse/ENG-474
> Calculate stage and other proportions over cycle-time

- src/sass/_variables.scss
- src/sass/components/_badges.scss
This adds the new color styles for the PR lables as commented on [#ENG-456](https://athenianco.atlassian.net/browse/ENG-456).
- Work in progress:
- Review:
- Merge:
- Release:
> Adding styles for the new PR labels

- src/js/components/insights/Insights.jsx
- src/js/hooks.jsx
- src/js/pages/pipeline/Pipeline.jsx
- src/js/pages/pipeline/Stage.jsx
This refactors the `Stage` component that became a monster making changes too difficult without introducing new glitches. The refactor consists in pushing down the state management of the insights section related things into the `Insights` component itself.
> Push down insights state management

- src/js/pages/pipeline/Overview.jsx
Fixes broken summary chart of overview section after merging #182.
> Fix summary chart of Overview section

- src/js/components/charts/FilledAreaChart.jsx
- src/js/pages/pipeline/Overview.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/services/format.js
Fixes y-values in Summary Charts and average.
> Summary chart y values

- src/js/components/charts/Chart.jsx
- src/js/components/pipeline/PipelineCardMiniChart.jsx
- src/js/components/pipeline/Thumbnails.jsx
Make mini-charts behaves as the summary metrics.
> Mini chart fixes

- public/config.js
- public/index.html
- src/js/context/User.jsx
Closes [ENG-479](https://athenianco.atlassian.net/browse/ENG-479).
Depends on: https://github.com/athenianco/infrastructure/pull/75/files
> Adds Intercom integration

- src/js/components/insights/stages/merge/mergeDelays.jsx
Fix https://athenianco.atlassian.net/browse/ENG-501
> Fix Merge KPI title

- src/js/services/api/index.js
> Increase default api timeout to 5mins

- src/js/pages/pipeline/Pipeline.jsx
Fix https://athenianco.atlassian.net/browse/ENG-502
> Improve naming of summary metrics

- src/js/components/charts/FilledAreaChart.jsx
- src/js/services/format.js
This PR adds dynamic y-label unit selection for summary charts depending on the maximum value. This also adds dynamic unit selection for each individual value for the tooltips.
> Summary charts values formatting

- src/js/services/api/index.js
Closes [ENG-478](https://athenianco.atlassian.net/browse/ENG-478).
This PR fixes the calculation of the main metrics and uses the `all` granularity to make queries more lightweight.
> Fix calculation of main metrics and variations

- src/js/components/charts/Tooltip.jsx
- src/js/components/insights/charts/library/HorizontalBarChart.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/pages/prototypes/Tooltips.jsx
required by [ENG-461]
0c4d521 Implement 'User with PRs, reviews, and comment' tooltip, which will act as:
- `User with PRs and comments`
- `User Reviews comments`
- `User Reviews`
To be used in:
- Review Activity
[ENG-461]: https://athenianco.atlassian.net/browse/ENG-461
> User with prs comments

- src/js/components/charts/Tooltip.jsx
caused by https://github.com/athenianco/athenian-webapp/pull/199
> Fix 'User with PRs, reviews and comment' tooltip

- src/js/components/insights/Insights.jsx
- src/js/context/PRs.jsx
- src/js/pages/pipeline/Body.jsx
- src/js/pages/pipeline/Overview.jsx
- src/js/pages/pipeline/PullRequests.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/services/api/index.js
Closes [ENG-478](https://athenianco.atlassian.net/browse/ENG-478).
This PR fixes the query for the variation badges and implements the calculation of the variation for PRs and Contributors top metrics (it was static).
> Fix comparison period

- src/js/components/charts/Tooltip.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
To be used in:
- Most Active Developer
> Implement tooltip in Most Active Developer

- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
- src/js/services/format.js
solves [[ENG-462]]
ses my comments in [[ENG-462]]
[ENG-462]: https://athenianco.atlassian.net/browse/ENG-462
[ENG-462]: https://athenianco.atlassian.net/browse/ENG-462
> Use proper userImageIndex from exported github formatter

- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
close [[ENG-539]]
[ENG-539]: https://athenianco.atlassian.net/browse/ENG-539
> Rename 'Most Active Devs' chart as 'Pull Request Authors'

- src/js/components/pipeline/PullRequests.jsx
> Remove stage usage from pr object

- src/js/pages/pipeline/PullRequests.jsx
- src/js/services/api/index.js
This reduces the number of queries to `filter/pull_request`.
> Fix useEffect for calling filter/pull_request

- src/js/components/charts/Tooltip.jsx
- src/js/components/insights/charts/library/BubbleChart.jsx
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/pages/prototypes/charts/VerticalBarChart.jsx
closes [[ENG-532]]
Persistent tooltips won't disappear till the user:
- clicks on the chart
- hovers another point
- leaves the chart
The persistence feature was added only to the tooltip with that requirement:
- `Pull Request Size` chart tooltips.
[ENG-532]: https://athenianco.atlassian.net/browse/ENG-532
> Persistent tooltips

- package.json
- src/js/components/pipeline/PullRequests.jsx
This is just a proposal! https://athenianco.atlassian.net/browse/ENG-534
I changed the PR number format in the list to match GitHub: https://github.com/athenianco/athenian-api/pull/215
> Change pr number format

- src/js/services/prHelpers.js
fix [[ENG-495]]
[ENG-495]: https://athenianco.atlassian.net/browse/ENG-495
> Fix participants. A participant can be author and have other roles

- src/js/components/insights/stages/review/reviewActivity.jsx
Total Reviewers must count reviewers, instead of commenters
> Fix Review Activity Chart

- src/js/components/insights/stages/merge/mergeDelays.jsx
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
- src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
https://athenianco.atlassian.net/browse/ENG-460
> Add chart descriptions in the info tooltips

- src/js/components/insights/KPI.jsx
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
> Fix review insights

- src/js/components/insights/charts/library/TimeSeries.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
https://athenianco.atlassian.net/browse/ENG-564
> Add the average line with tooltips for the Wait Time for Review chart

- src/js/components/charts/FilledAreaChart.jsx
https://athenianco.atlassian.net/browse/ENG-533
> Add 2 tooltips over the extremities of the average line

- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/pipeline/PullRequests.jsx
- src/js/pages/pipeline/Pipeline.jsx
- src/js/services/prHelpers.js
- src/sass/components/_badges.scss
Closes [ENG-556](https://athenianco.atlassian.net/browse/ENG-556) and [ENG-560](https://athenianco.atlassian.net/browse/ENG-560).
This PR also adds two new labels for the PRs in review stage:
- "Not Reviewed",
- "Review Ignored"
_*Colors are to be eventually redefined later_
> Prs tables fixes

- src/sass/components/_pipeline.scss
https://athenianco.atlassian.net/browse/ENG-561
> Add hover effects on the timeline events

- src/js/pages/pipeline/Pipeline.jsx
https://athenianco.atlassian.net/browse/ENG-573
> Rename the Overview block to Lead Time

- src/js/components/pipeline/PullRequests.jsx
Fix [[ENG-577]]
[ENG-577]: https://athenianco.atlassian.net/browse/ENG-577
> Filter PRs by label

- src/js/pages/auth/Callback.jsx
> Avoid accepting invitation more than once

- src/js/components/insights/stages/review/reviewActivity.jsx
required by [[ENG-489]]
[ENG-489]: https://athenianco.atlassian.net/browse/ENG-489
> Show raw ratio of PRs created/reviewed, without gcd

- src/js/Routes.jsx
- src/js/components/layout/Breadcrumbs.jsx
- src/js/context/Breadcrumbs.jsx
- src/js/pages/Waiting.jsx
- src/js/pages/prototypes/Waiting.jsx
- src/js/pages/prototypes/index.jsx
- src/js/pages/templates/Simple.jsx
- src/sass/base/_utilities.scss
- src/sass/components/_pipeline.scss
caused by [[ENG-338]] Enhance user registration and flow through the waiting page
a4f2cee Fix Breadcrumbs and Pages out of UserContext
- 903bdad Add a prototype for the Waiting page
- ae3b666 Simplify Waiting page
[ENG-338]: https://athenianco.atlassian.net/browse/ENG-338
> Waiting page

- src/js/services/prHelpers.js
Closes [ENG-608](https://athenianco.atlassian.net/browse/ENG-608).
> Fix labels for PRs in overview table

- src/js/components/insights/charts/library/BubbleChart.jsx
- src/js/components/insights/charts/library/HorizontalBarChart.jsx
- src/js/pages/prototypes/charts/HorizontalBarChart.jsx
- src/js/pages/prototypes/charts/VerticalBarChart.jsx
- src/sass/components/_charts.scss
https://athenianco.atlassian.net/browse/ENG-639
> Set up a uniform styling chart legends

- src/sass/components/_tooltips.scss
https://athenianco.atlassian.net/browse/ENG-640
> Add hover effect on the PR titles of the PR Size chart tooltips

- src/js/components/insights/charts/library/BubbleChart.jsx
https://athenianco.atlassian.net/browse/ENG-641
> Improve the bubble scaling in the PR size chart

- src/js/pages/pipeline/Filters.jsx
Closes [ENG-636](https://athenianco.atlassian.net/browse/ENG-636).
> Properly reset cached data on filter change

- src/js/pages/pipeline/Pipeline.jsx
https://athenianco.atlassian.net/browse/ENG-655
This PR removes two duplicated queries that were occurring during the filters preparation.
> Removes glitch in useEffect during pipeline context init due to not ready filters

- src/js/components/pipeline/Thumbnails.jsx
Fixes the broken active card style on mini-chart. I broke it during some of the previous perf improvements.
> Fix broken active card style

- src/js/components/ui/filters/DateInterval.jsx
> Fix initial date intervals

- src/js/pages/pipeline/Filters.jsx
> Fix global data set on date interval change

- src/js/components/insights/stages/review/reviewActivity.jsx
PRs from `/metrics/prs` and `metrics/developers` are not returning
exactly the same data as filtering from the already retrieved prs.
> Use SummaryMetric definitions for ReviewActivity Created/Reviewed KPIs

- src/js/components/ui/filters/MultiSelect.jsx
- src/sass/components/_datepicker.scss
https://athenianco.atlassian.net/browse/ENG-660
https://www.loom.com/share/55ef1dafed054ebbab9b4d9a6eedc416
> Add pointer cursors for the 3 top level filters

- src/js/components/insights/Insights.jsx
- src/js/components/layout/Empty.jsx
- src/js/pages/prototypes/EmptyStates.jsx
closes [[ENG-634]]
[ENG-634]: https://athenianco.atlassian.net/browse/ENG-634
> Add Comming soon into releases

- src/js/components/layout/Navbar.jsx
You can still access by direct url, but the settings link will no longer in the user menu till it's approved
> Hide settings from user menu

- src/js/pages/pipeline/Pipeline.jsx
> Better handling of multi-granularity in Pipeline

- src/js/Routes.jsx
- src/js/pages/prototypes/ReleaseSettings.jsx
- src/sass/base/_utilities.scss
- src/sass/components/_accordions.scss
- src/sass/components/_dropdowns.scss
- src/sass/components/_forms.scss
- src/sass/components/_tables.scss
- src/sass/main.scss
This is related to the issue [#ENG-668](https://athenianco.atlassian.net/browse/ENG-668). 
I added the prototype template for the Release settings page.
> Adding prototype for the Release settings page

- src/js/components/layout/Empty.jsx
- src/js/components/pipeline/PullRequests.jsx
- src/js/pages/Settings.jsx
- src/js/pages/Waiting.jsx
- src/js/pages/auth/Login.jsx
- src/js/pages/pipeline/Overview.jsx
- src/js/pages/pipeline/Stage.jsx
- src/js/pages/prototypes/ReleaseSettings.jsx
- src/js/pages/prototypes/Waiting.jsx
required by [[ENG-584]] Gracefully handle the case when no data is available given the data range selected
This PR handles loading and empty state in PRs tables.
https://www.loom.com/share/82a93ebd3042411e99d6d0e663b2e41e
[ENG-584]: https://athenianco.atlassian.net/browse/ENG-584
> Handle empty and loading state in PRs tables

- src/js/components/ui/filters/DateInterval.jsx
https://athenianco.atlassian.net/browse/ENG-699
> Shift initialVisibleMonth by 1 month in the DateRangePicker

- src/js/pages/pipeline/Filters.jsx
Closes [ENG-674](https://athenianco.atlassian.net/browse/ENG-674).
> Properly set an awaitable object to filter.repos and filter.contribs global data on date change

- src/js/components/DataWidget.jsx
- src/js/components/insights/Helper.jsx
- src/js/components/insights/Insights.jsx
- src/js/components/insights/stages/merge/index.jsx
- src/js/components/insights/stages/merge/mergeDelays.jsx
- src/js/components/insights/stages/review/index.jsx
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/components/insights/stages/work-in-progress/index.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
- src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
- src/js/pages/pipeline/Body.jsx
Improves performances for loading the review stage: reduces the requests from 15 to 12, from 25s to 19s, that is -24%.
> Insights charts requests

- src/js/components/pipeline/MainMetrics.jsx
https://athenianco.atlassian.net/browse/ENG-694
> Change the PR count for the number of Pull Requests released

- public/config.js
- public/index.html
- src/js/App.jsx
- src/js/Routes.jsx
- src/js/Routes.test.js
- src/js/analytics.js
- src/js/context/User.jsx
Closes [ENG-614](https://athenianco.atlassian.net/browse/ENG-614).
Blocked by [ENG-728](https://athenianco.atlassian.net/browse/ENG-728).
Intercom integration has been done in Segment dashboard, missing GA and MP integrations.
> Segment integration

- src/js/components/charts/FilledAreaChart.jsx
- src/js/components/insights/stages/merge/mergeDelays.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
- src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
- src/js/components/layout/Empty.jsx
- src/js/pages/pipeline/Body.jsx
- src/js/services/api/index.js
- src/js/services/format.js
- b37ba55 Handle no data situations, e.g. ancient dates
- a71e18d Use format.number.fixed(n,d) instead of n.toFixed(d)
> Fix some random errors that broke the page

- src/js/components/pipeline/Thumbnails.jsx
> Remove debug leftover

- src/js/services/prHelpers.js
Fix https://athenianco.atlassian.net/browse/ENG-671
> Fix Changes Requested showing for merged PRs

- src/js/components/pipeline/MainMetrics.jsx
- src/js/pages/pipeline/Body.jsx
Note: I am not sure why but it still displays the number of released PRs. Please help to finish this :smile:
> Use pr-all-count

- src/js/components/pipeline/MainMetrics.jsx
This reverts commit 5f4b49d60d614784b5ecb6e310fa23b246b5a67f.
> Revert "Use pr-all-count"

- src/js/services/api/index.js
Fixes the values passed to api for developers filter introduced by #299.
> Fix filter values passed to api

- src/js/components/insights/charts/library/HorizontalBarChart.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-747
Add prop tickFormat
Steps:
1) http://localhost:3000/stage/review
2) Scroll to insights
3) Horizontal bar chart now has '%' in its tickformat
> feat(ENG-747): Add tickformat to Review Activity

- src/js/components/insights/stages/review/pullRequestSize.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-711
On Bubble chart (Pull Request Size), show count of changed files only if not reviewed yet
> fix(ENG-711): Fix files changed count on Bubble chart

- .travis.yml
> Fix Sentry releases preparation in CI deploy stage

- .travis.yml
- Dockerfile
> Use a separate docker containaer to do the Sentry release

- src/js/components/charts/Tooltip.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-748
Replaces icons from Tooltip
> refactor(ENG-748): Replace review and PR icons on Review Activity chart

- src/js/components/development/index.scss
Quick fix for Bearer token wrap
> fix: Bearer token wrap on /bearer

- package.json
- src/js/App.jsx
- src/js/pages/settings/Releases.jsx
- src/js/services/logger.jsx
- src/sass/main.scss
- yarn.lock
required by [[ENG-696]] Add the release settings page into the current settings of the webapp
Success and error messages when calling API through Release settings will be shown using [react-toastify](https://fkhadra.github.io/react-toastify/introduction)
[ENG-696]: https://athenianco.atlassian.net/browse/ENG-696
> Show success/error messages in toast

- src/js/pages/Settings.jsx
- src/js/pages/settings/Releases.jsx
- src/js/pages/settings/Team.jsx
closes [[ENG-789]] Enable the filter feature in the Settings pages
In settings, filters by project name
https://www.loom.com/share/befeaa66e2024e0f9e68a9c938b2ee63
In teams, filters by user name or handler
https://www.loom.com/share/68453d4078b5486aa46360cf59fde7e3
[ENG-789]: https://athenianco.atlassian.net/browse/ENG-789
> Enable filtering in Release and Team settings

- src/js/components/insights/charts/library/HorizontalBarChart.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-749
Replace `reviews` metric by `prs-reviewed`
> fix(ENG-749): Replace Reviews count by Prs Reviewed

- src/js/components/pipeline/PullRequests.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-778
> feat(ENG-778): Add filter by status to PRs table

- src/js/pages/auth/Callback.jsx
- src/js/services/api/index.js
Closes [ENG-784](https://athenianco.atlassian.net/browse/ENG-784).
Adds a wrapper to use on all api requests in order to be able to track errors on Sentry due to non-200 responses.
> Better sentry errors

- src/js/components/pipeline/PullRequests.jsx
- src/js/pages/pipeline/Overview.jsx
- src/sass/components/_tables.scss
> fix(): Filter cropping/Filter options by context

- src/js/components/insights/stages/review/reviewActivity.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-801
> fix(ENG-801): fix average PR reviews per developer

- src/js/pages/Settings.jsx
As suggested by @se7entyse7en during code review https://github.com/athenianco/athenian-webapp/pull/319/files#r423721591
Signed-off-by: David Pordomingo <david.pordomingo.f@gmail.com>
> Enable Teams link in Settings aside for Staging

- src/js/components/charts/Tooltip.jsx
- src/js/components/ui/Typography.jsx
- src/js/pages/prototypes/Tooltips.jsx
- src/js/services/api/index.js
No cosmetics changes
- 0d191c8 Rename Tooltips/SmallTitle into Typography/AltTitle to avoid collisions with the older one
- cd13030 Log in console errors sent to Sentry
> Misc. Show errors sent by Sentry in the console

- src/js/pages/settings/Releases.jsx
solves [[ENG-833]]
Use `branch_name` as placeholder for the branch pattern input.
[ENG-833]: https://athenianco.atlassian.net/browse/ENG-833
> Releases pattern

- src/js/components/pipeline/StageMetrics.jsx
- src/js/services/format.js
- src/sass/components/_pipeline.scss
addresses [[ENG-779]] Fix the NAN and style the tooltip of the Lead Time distribution chart
**TODO:**
- to style the tooltip.
[ENG-779]: https://athenianco.atlassian.net/browse/ENG-779
> Overview bars

- src/js/components/ui/filters/MultiSelect/CustomComponents.jsx
Minor fixes from review of ENG-291
https://github.com/athenianco/athenian-webapp/pull/321
> fix(ENG-291): fixes from review of 291

- src/js/components/insights/stages/review/pullRequestSize.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-830
> fix(ENG-830): Fix average # of files changed in reviews sections

- src/js/services/prHelpers.js
> [HOTFIX] Fix missing .value() call to loadash wrapper

- src/js/services/prHelpers.js
> Fix PRs filtering for tables

- src/js/App.jsx
- src/js/components/insights/KPI.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
- src/js/components/ui/Badge.jsx
- src/js/services/prHelpers.js
- src/js/smart-components/ErrorBoundary.jsx
revert mocked error from https://github.com/athenianco/athenian-webapp/pull/336
> Revert sentry err

- src/js/pages/pipeline/Body.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-776
> fix(ENG-776): Fix flashing no-data placeholder

- src/js/components/insights/KPI.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/pages/pipeline/Body.jsx
solves [[ENG-844]] Metric computational errors displayed as yellow badges in the UI
[ENG-844]: https://athenianco.atlassian.net/browse/ENG-844
> Fix divisions by zero and NaN when missing data

- src/js/pages/Settings.jsx
caused by https://github.com/athenianco/athenian-webapp/pull/340
> Fix local welcomed panel storage key

- src/js/components/pipeline/PullRequests.jsx
- src/js/components/ui/Info.jsx
- src/sass/components/_tables.scss
- src/sass/components/_tooltips.scss
fix [[ENG-888]] Allow to search PRs by repo name in the tables
This also adds a tooltip with a hint about the available filters
[ENG-888]: https://athenianco.atlassian.net/browse/ENG-888
> Filter PRs by repo title

- src/js/analytics.js
- src/js/context/User.jsx
Closes [ENG-629](https://athenianco.atlassian.net/browse/ENG-629).
> No god tracking

- src/js/context/User.jsx
- src/js/services/api/index.js
Closes [ENG-930](https://athenianco.atlassian.net/browse/ENG-930).
> Fix onboarding waiting page

- src/js/analytics.js
> Better analytics debugging

- public/index.html
- src/js/analytics.js
> Add more instrumentation for degugging Segment integration

- src/js/components/charts/Tooltip.jsx
- src/js/components/insights/charts/library/TimeSeries.jsx
- src/js/components/insights/charts/library/VerticalBarChart.jsx
- src/js/components/insights/stages/work-in-progress/createdPrs.jsx
- src/js/components/insights/stages/work-in-progress/index.jsx
[[ENG-761]] WIP: Pull Requests created through time
I found no specs for the KPIs, so I used the same logic than for PR Ratio Flow chart:
- Average of PRs created by day,
- Day when more PRs were created.
[ENG-761]: https://athenianco.atlassian.net/browse/ENG-761
> Chart created prs

- src/js/components/ui/filters/MultiSelect/CustomComponents.jsx
- src/js/pages/pipeline/Filters/index.jsx
- src/js/pages/settings/Team.jsx
- src/sass/components/_filters.scss
Closes: https://athenianco.atlassian.net/browse/ENG-889
> fix(ENG-889): Change the color of the GitHub handles from light grey to black when there is no full names

- src/js/components/ui/filters/MultiSelect/CustomComponents.jsx
- src/js/components/ui/filters/MultiSelect/CustomStyles.jsx
- src/sass/components/_filters.scss
This is related to #ENG-953. It adds a new color scheme to the filters to make the UI lighter. It also adds minor style improvements.
> Improving filters background colors to make it lighter

- src/js/pages/settings/Team.jsx
> Remove rename option

- src/js/pages/pipeline/Filters/index.jsx
> Fix call to getTeams after interface change

- src/js/pages/settings/Team.jsx
Closes [ENG-969](https://athenianco.atlassian.net/browse/ENG-969).
> Fix initial checked members for team members add

- src/js/components/layout/Footer.jsx
This is related to the issue [#ENG-964](https://athenianco.atlassian.net/browse/ENG-964). It adds new styles to improve the footer design:
> Improving footer design

- src/js/components/ui/filters/MultiSelect/CustomComponents.jsx
This adds handling of indeterminate state.
> Add indeterminate state for Group checkbox

- src/js/components/pipeline/PullRequests.jsx
[[ENG-908]] Tooltip gets stuck on the page
[ENG-908]: https://athenianco.atlassian.net/browse/ENG-908
> Filter PRs using datatable.net search method

- src/js/pages/Settings.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-957
> fix(ENG-957): Fix the breakdown arrows in the team set up

- src/js/pages/settings/Team.jsx
Closes: https://athenianco.atlassian.net/browse/ENG-970
> fix(ENG-970): Apply the same styling for the GitHub handles of the 2 listings

- src/js/components/pipeline/PullRequests.jsx
- src/js/services/prHelpers.js
- src/sass/components/_tables.scss
solves [[ENG-960]] Sort the stage column of the PR table chronologically
[ENG-960]: https://athenianco.atlassian.net/browse/ENG-960
> Sort PR table by custom label order

- src/js/pages/Settings.jsx
https://athenianco.atlassian.net/browse/ENG-984
> Enable Teams Settings Link

- src/js/services/prHelpers.js
fix [[ENG-961]] Closed PRs should not appear in the PR table of the Release section
- Closed PRs should contain as completed stages only those that received their proper transition event
- Closed PRs should not appear in Release stage
[ENG-961]: https://athenianco.atlassian.net/browse/ENG-961
> Change isInStage and extractCompletedStages logic for closed PRs

- .travis.yml
- Makefile
- Makefile.testenv
- docs/CONTRIBUTING.md
- docs/testing.md
close [[ENG-814]]
[ENG-814]: https://athenianco.atlassian.net/browse/ENG-814
> makefile commands for pre-staging test environments

- src/js/components/insights/stages/merge/mergeDelays.jsx
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
- src/js/components/insights/stages/work-in-progress/createdPrs.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
Fix [ENG-992](https://athenianco.atlassian.net/browse/ENG-992)
> Fix copy in axis labels, legends and KPIs

- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
> Reduce the number max of devs showed in the hbar charts

- src/js/components/pipeline/PullRequests.jsx
closes [[ENG-987]] Adjust the PR sorting strategy by label in case of equality
Sort PRs table by `label asc, creation desc`
[ENG-987]: https://athenianco.atlassian.net/browse/ENG-987
> Sort PRs table by label asc, creation desc

- src/js/components/charts/Tooltip.jsx
- src/js/components/insights/charts/library/VerticalBarChart.jsx
- src/js/components/insights/stages/merge/mergeDelays.jsx
- src/js/components/insights/stages/work-in-progress/index.jsx
- src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
required by [[DEV-138]] [new chart] WIP: Pull Requests Created per repo
only one KPI available: Average of PRs
[DEV-138]: https://athenianco.atlassian.net/browse/DEV-138
> Add new Wip chart. Pull Requests per Repo

- src/js/components/insights/stages/review/waitTimeFirstReview.jsx
[[DEV-176]] Remove the diff badge for the Proportion of Cycle Time KPI
[DEV-176]: https://athenianco.atlassian.net/browse/DEV-176
> Remove variation badge in wait time for 1st review

- package.json
- src/js/App.jsx
- src/js/Routes.jsx
- src/js/components/layout/Navbar.jsx
- src/js/context/User.jsx
- src/js/hooks.jsx
- src/js/pages/Demo.jsx
- src/js/pages/Settings.jsx
- src/js/pages/auth/Login.jsx
- src/js/pages/pipeline/Filters/index.jsx
- src/js/pages/templates/Page.jsx
- yarn.lock
Closes [DEV-162](https://athenianco.atlassian.net/browse/DEV-162).
This adds the possibility to see Athenian data in demo mode:
- to activate demo mode the user needs to visit `/demo`, it will set a cookie and will redirect to home showing the Athenian's data,
- during the demo, instead of the user avatar, the "Login" button is shown as if a user is not authenticated,
- to deactivate demo mode the user can visit `/undemo`,
- demo mode is deactivated automatically when going to `/login`,
- demo mode is deactivated also after 1h of "inactivity" (the cookie expires after 1h, but it refreshes on each page refresh or navigation, for example, navigating through the stages),
- in demo mode, a user cannot go to the settings page.
> Public athenian

- src/js/context/User.jsx
> No track of identity during demo mode

- src/js/components/charts/Tooltip.jsx
- src/js/components/insights/charts/library/VerticalBarChart.jsx
- src/js/components/insights/stages/merge/abandonedWork.jsx
- src/js/components/insights/stages/merge/index.jsx
- src/js/components/insights/stages/review/pullRequestSize.jsx
- src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
- src/js/services/format.js
required by [[DEV-137]] [new chart] Abandoned Work
This PR includes some other enhancements:
- 3cb4bdf Define a default user image for unknown users
- Enhance `VerticalBarChart`:
- bbd12f0 Make the left margin configurable
- 9bbffa6 Let the tooltip to be persistent
- 95195ff Make the YAxis ticks to be configurable
- dd97124 Add an optional average line
- **Tooltip for the average.** We currently have no charts with the capacity of having two different tooltips, so I need to investigate a bit. In the meanwhile, there won't be a tooltip for the average.
[DEV-137]: https://athenianco.atlassian.net/browse/DEV-137
> New Chart: Merge > Abandoned work

- src/js/components/insights/stages/merge/index.jsx
caused by https://github.com/athenianco/athenian-webapp/pull/409
> Hide Abandoned Work chart in Prod

- src/js/components/insights/charts/library/BubbleChart.jsx
- src/js/components/insights/charts/library/TimeSeries.jsx
solves [[DEV-187]] Fix the chart axis showing negative values
[DEV-187]: https://athenianco.atlassian.net/browse/DEV-187
> Avoid negative numbers in axis 

- src/js/components/ui/filters/MultiSelect/index.jsx
Closes [DEV-211](https://athenianco.atlassian.net/browse/DEV-211) which was a regression introduced by https://github.com/athenianco/athenian-webapp/pull/413.
> Fix repos and devs filter opening together

- src/js/components/ui/filters/DateInterval.jsx
> Fix DateInterval footer component

- src/js/pages/pipeline/Pipeline.jsx
- src/js/services/prHelpers.js
fix [[DEV-141]] Show the number of PRs stage-pending in the stage cards
[DEV-141]: https://athenianco.atlassian.net/browse/DEV-141
> Show stage-complete count in stage thumbnails

- src/js/services/api/index.js
Revert: https://github.com/athenianco/athenian-webapp/pull/422
> Send exclude_inactive even when false, reverting back a previous hotfix

- src/js/components/ui/filters/MultiSelect/index.jsx
- src/js/pages/pipeline/Filters/index.jsx
Closes [DEV-232](https://athenianco.atlassian.net/browse/DEV-232).
> Handling no teams

- src/js/components/insights/stages/merge/abandonedWork.jsx
- src/js/components/insights/stages/review/reviewActivity.jsx
- src/js/components/insights/stages/work-in-progress/createdPrs.jsx
- src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
- src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
- src/js/components/pipeline/PullRequests.jsx
- src/js/components/ui/filters/DateInterval.jsx
- src/js/pages/pipeline/Pipeline.jsx
Fix https://athenianco.atlassian.net/browse/DEV-233
> Fix copies in the tooltips

- src/js/components/ui/filters/MultiSelect/index.jsx
Closes [DEV-237](https://athenianco.atlassian.net/browse/DEV-237).
> Fix applied values in MultiSelect when `uniquenessKey` is defined

- src/js/pages/pipeline/Filters/index.jsx
> Hotfix contribs by ensuring they're unique when storing as global data
